(in-package :slipstream)

(defstruct (v (:constructor v (x y z))) (x 0.0f0) (y 0.0f0) (z 0.0f0))
(defun v+ (a b) (v (+ (v-x a) (v-x b)) (+ (v-y a) (v-y b)) (+ (v-z a) (v-z b))))
(defun v- (a b) (v (- (v-x a) (v-x b)) (- (v-y a) (v-y b)) (- (v-z a) (v-z b))))
(defun v* (a n) (v (* (v-x a) n) (* (v-y a) n) (* (v-z a) n)))
(defun dot3 (a b) (+ (* (v-x a) (v-x b)) (* (v-y a) (v-y b)) (* (v-z a) (v-z b))))
(defun len (a) (sqrt (dot3 a a)))
(defun unit (a) (let ((n (len a))) (if (< n 0.00001) (v 0 0 0) (v* a (/ n)))))
(defun flat (a) (v (v-x a) 0 (v-z a)))
(defun distance3 (a b) (len (v- a b)))
(defun clamp (x lo hi) (min hi (max lo x)))
(defun rnd (a b) (+ a (* (random 1.0f0) (- b a))))
(defun direction (yaw pitch) (v (* (- (sin yaw)) (cos pitch)) (sin pitch) (* (- (cos yaw)) (cos pitch))))
(defun angle-to (a b)
  (let ((x (- (v-x a) (v-x b))) (z (- (v-z a) (v-z b))))
    (if (< (+ (abs x) (abs z)) 0.000001) 0.0 (atan x z))))
(defun angle-delta (a b) (- (mod (+ (- a b) pi) (* 2 pi)) pi))
(defconstant +radius+ 0.42f0)
(defconstant +height+ 1.8f0)
(defconstant +tick+ (/ 1.0f0 120))
(defparameter *weapon-names* #("ION CARBINE" "SCATTERGUN" "ROCKET LAUNCHER" "RAIL DRIVER"))
(defparameter *weapon-colors* #(#x4AE5DAFF #xFFBE5BFF #xFF6A43FF #xB78BFFFF))
(defparameter *bot-names* #("VEX" "KERNEL" "NYX" "GHOST" "RIFT" "NULL" "AXIOM"))
(defparameter *bot-colors* #(#xFF785FFF #xB68AFFFF #xE7BB57FF #x76BBFFFF #xF380B8FF #x80D785FF #xDDDDEEFF))
(defstruct (solid (:conc-name block-) (:constructor make-block)) pos size (color #x526072FF) (accent #x4AE5DAFF))
(defstruct actor name color pos (vel (v 0 0 0)) (yaw 0.0f0) (pitch 0.0f0)
  (hp 100) (armor 25) (frags 0) (deaths 0) (bot nil) (weapon 0)
  (ammo (vector 180 24 16 16)) (ground nil) (cool 0.0f0) (dead 0.0f0)
  (invuln 0.0f0) (wall-cool 0.0f0) (dash-cool 0.0f0) (pad-cool 0.0f0)
  (jump-buffer 0.0f0) (think 0.0f0) goal path target (walk 0.0f0) (recoil 0.0f0)
  (stuck 0.0f0) (last-pos (v 0 0 0)) (kills 0) (wall-kicks 0) (shots 0) (hits 0))
(defstruct pickup pos kind (timer 0.0f0))
(defstruct rocket pos vel owner (life 4.0f0))
(defstruct effect from to color (life 0.15f0) (max-life 0.15f0) (radius 0.03f0) (kind :beam))
(defvar *blocks* nil)
(defvar *actors* nil)
(defvar *player* nil)
(defvar *pickups* nil)
(defvar *rockets* nil)
(defvar *effects* nil)
(defvar *feed* nil)
(defvar *time* 0.0f0)
(defvar *match-left* 300.0f0)
(defvar *state* :menu)
(defvar *difficulty* 1)
(defvar *bot-count* 4)
(defvar *frag-limit* 20)
(defvar *sensitivity* 0.0022f0)
(defvar *fov* 90.0f0)
(defvar *hit-flash* 0.0f0)
(defvar *damage-flash* 0.0f0)
(defvar *kick-flash* 0.0f0)
(defvar *notice* "")
(defvar *notice-time* 0.0f0)
(defvar *music* nil)
(defvar *nav* nil)
(defvar *nav-links* nil)
(defvar *spawns* nil)
(defvar *pads* nil)

(defun add-block (x y z w h d &optional (color #x526072FF) (accent #x4AE5DAFF))
  (push (make-block :pos (v x y z) :size (v w h d) :color color :accent accent) *blocks*))
(defun box-min (b) (v- (block-pos b) (v* (block-size b) 0.5f0)))
(defun box-max (b) (v+ (block-pos b) (v* (block-size b) 0.5f0)))
(defun in-footprint (p b &optional (margin 0))
  (let ((lo (box-min b)) (hi (box-max b)))
    (and (< (- (v-x lo) margin) (v-x p) (+ (v-x hi) margin))
         (< (- (v-z lo) margin) (v-z p) (+ (v-z hi) margin)))))
(defun floor-at (x z &optional (below 100))
  (let ((y 0.0f0) (p (v x 0 z)))
    (dolist (b *blocks* y)
      (let ((top (v-y (box-max b))))
        (when (and (in-footprint p b) (<= top below)) (setf y (max y top)))))))

(defun make-arena ()
  (setf *blocks* nil *pickups* nil)
  (add-block -29 7 0 2 14 60 #x39495EFF)
  (add-block 29 7 0 2 14 60 #x39495EFF #xFFAA66FF)
  (add-block 0 7 -29 56 14 2 #x39495EFF)
  (add-block 0 7 29 56 14 2 #x39495EFF #xFFAA66FF)
  (dolist (side '(-1 1))
    (let ((accent (if (= side -1) #x4AE5DAFF #xFFAA66FF)))
      (add-block (* side 22) 1.6 0 12 3.2 22 #x48576CFF accent)
      (dotimes (i 10)
        (let ((height (* (- 10 i) 0.32)))
          (add-block (* side (+ 10.4 (* (- 9 i) 0.56))) (/ height 2) 0 0.56 height 7 #x59677AFF accent)))
      (add-block 0 2.5 (* side 24) 14 5 8 #x46566BFF accent)
      (dotimes (i 16)
        (let ((height (* (1+ i) 0.3125)))
          (add-block 0 (/ height 2) (* side (+ 11.6 (* i 0.52))) 6 height 0.52 #x5C697AFF accent)))
      (dolist (z '(-9 9)) (add-block (* side 9) 3.5 z 2.4 7 2.4 #x3B4658FF accent))
      (dolist (z '(-19 19)) (add-block (* side 12) 0.85 z 4 1.7 3 #x586476FF accent))))
  (add-block 0 0.6 0 7 1.2 7 #x6A6872FF #xB78BFFFF)
  (setf *pads* (list (v -23 0 -20) (v 23 0 20) (v -23 0 20) (v 23 0 -20)))
  (dolist (spec '((0 1.2 0 :mega) (-22 3.2 -7 :rail) (22 3.2 7 :rockets)
                 (0 5 -24 :armor) (0 5 24 :mega) (-18 0 -19 :health)
                 (18 0 19 :health) (18 0 -18 :shells) (-18 0 18 :shells)
                 (0 0 -7 :ammo) (0 0 7 :ammo) (-22 3.2 7 :armor) (22 3.2 -7 :health)))
    (destructuring-bind (x y z kind) spec
      (push (make-pickup :pos (v x (+ y 0.1) z) :kind kind) *pickups*)))
  (setf *blocks* (nreverse *blocks*)
        *spawns* (mapcar (lambda (xz) (v (first xz) (floor-at (first xz) (second xz)) (second xz)))
                        '((-20 -24) (20 24) (-20 24) (20 -24) (-22 -8) (22 8) (0 -25) (0 25) (-5 -15) (5 15))))
  (build-nav))

;; A small, fixed arena uses a sampled navigation graph, with real height changes.
;; ponytail: an O(n) open-set scan is sufficient for this 700-node offline arena.
(defun build-nav ()
  (let ((nodes (make-array 0 :adjustable t :fill-pointer 0)) (grid (make-hash-table :test #'equal)))
    (loop for ix from -17 to 17 do
      (loop for iz from -17 to 17 do
        (let* ((x (* ix 1.5)) (z (* iz 1.5)) (y (floor-at x z)) (p (v x y z)))
          (when (and (< y 6) (not (some (lambda (b) (and (in-footprint p b 0.48) (> (v-y (box-max b)) (+ y 0.4)))) *blocks*)))
            (setf (gethash (cons ix iz) grid) (length nodes)) (vector-push-extend p nodes)))))
    (setf *nav* nodes *nav-links* (make-array (length nodes) :initial-element nil))
    (maphash (lambda (key idx)
               (dolist (delta '((1 0) (-1 0) (0 1) (0 -1) (1 1) (1 -1) (-1 1) (-1 -1)))
                 (let ((other (gethash (cons (+ (car key) (first delta)) (+ (cdr key) (second delta))) grid)))
                   (when other
                     (let* ((a (aref nodes idx)) (b (aref nodes other)) (rise (- (v-y b) (v-y a))))
                       (when (and (<= rise 2.0) (>= rise -5.0)
                                  (or (= (first delta) 0) (= (second delta) 0)
                                      (and (gethash (cons (+ (car key) (first delta)) (cdr key)) grid)
                                           (gethash (cons (car key) (+ (cdr key) (second delta))) grid))))
                         (push other (aref *nav-links* idx)))))))) grid)))
(defun nearest-node (p)
  (let ((best 0) (dist most-positive-single-float))
    (dotimes (i (length *nav*) best)
      (let ((d (distance3 p (aref *nav* i)))) (when (< d dist) (setf dist d best i))))))
(defun route (from to)
  (let* ((start (nearest-node from)) (end (nearest-node to)) (n (length *nav*))
         (cost (make-array n :initial-element most-positive-single-float))
         (parent (make-array n :initial-element -1)) (closed (make-array n :initial-element nil))
         (open (list start)))
    (setf (aref cost start) 0.0f0)
    (loop while open do
      (let ((current (reduce (lambda (a b)
                               (if (< (+ (aref cost a) (distance3 (aref *nav* a) (aref *nav* end)))
                                      (+ (aref cost b) (distance3 (aref *nav* b) (aref *nav* end)))) a b)) open)))
        (setf open (delete current open))
        (when (= current end)
          (return-from route (loop for i = end then (aref parent i) until (= i start) collect (aref *nav* i) into path finally (return (nreverse path)))))
        (setf (aref closed current) t)
        (dolist (next (aref *nav-links* current))
          (unless (aref closed next)
            (let ((new (+ (aref cost current) (distance3 (aref *nav* current) (aref *nav* next)))))
              (when (< new (aref cost next))
                (setf (aref cost next) new (aref parent next) current)
                (pushnew next open)))))))
    nil))

(defun body-overlaps (p b &optional (radius +radius+))
  (let ((lo (box-min b)) (hi (box-max b)))
    (and (in-footprint p b radius) (< (v-y p) (- (v-y hi) 0.015)) (> (+ (v-y p) +height+) (+ (v-y lo) 0.015)))))
(defun blocked (p) (some (lambda (b) (body-overlaps p b)) *blocks*))
(defun wall-normal (p)
  (let ((best 0.82) (normal nil))
    (dolist (b *blocks* normal)
      (let ((lo (box-min b)) (hi (box-max b)))
        (when (and (< (v-y p) (- (v-y hi) 0.2)) (> (+ (v-y p) 1.6) (v-y lo)))
          (when (< (- (v-z lo) +radius+) (v-z p) (+ (v-z hi) +radius+))
            (dolist (side (list (list (v-x lo) -1) (list (v-x hi) 1)))
              (let ((d (* (second side) (- (v-x p) (first side)))))
                (when (<= 0 d best) (setf best d normal (v (second side) 0 0))))))
          (when (< (- (v-x lo) +radius+) (v-x p) (+ (v-x hi) +radius+))
            (dolist (side (list (list (v-z lo) -1) (list (v-z hi) 1)))
              (let ((d (* (second side) (- (v-z p) (first side)))))
                (when (<= 0 d best) (setf best d normal (v 0 0 (second side))))))))))))

(defun move-body (a dt)
  (let* ((p (actor-pos a)) (velocity (actor-vel a)) (old-y (v-y p)))
    (dolist (axis '(x z))
      (let* ((delta (* dt (if (eq axis 'x) (v-x velocity) (v-z velocity))))
             (candidate (v (if (eq axis 'x) (+ (v-x p) delta) (v-x p)) (v-y p)
                           (if (eq axis 'z) (+ (v-z p) delta) (v-z p)))))
        (if (blocked candidate)
            (let ((step (v (v-x candidate) (+ (v-y candidate) 0.36) (v-z candidate))))
              (if (and (actor-ground a) (not (blocked step)))
                  (setf p step)
                  (if (eq axis 'x) (setf (v-x velocity) 0) (setf (v-z velocity) 0))))
            (setf p candidate))))
    (let* ((next-y (+ (v-y p) (* dt (v-y velocity))))
           (floor (floor-at (v-x p) (v-z p) (+ (v-y p) 0.38))))
      (setf (actor-ground a) nil)
      (if (and (<= (v-y velocity) 0) (<= next-y floor))
          (setf (v-y p) floor (v-y velocity) 0 (actor-ground a) t)
          (let ((candidate (v (v-x p) next-y (v-z p))))
            (if (and (> (v-y velocity) 0) (blocked candidate))
                (setf (v-y velocity) 0)
                (setf p candidate)))))
    (when (and (actor-ground a) (< (v-y p) (- old-y 1.4))) (sound-at 9 p 0.45))
    ;; The perimeter remains closed even after a rocket jump above the wall tops.
    (when (> (abs (v-x p)) 27.57) (setf (v-x p) (clamp (v-x p) -27.57 27.57) (v-x velocity) 0))
    (when (> (abs (v-z p)) 27.57) (setf (v-z p) (clamp (v-z p) -27.57 27.57) (v-z velocity) 0))
    (setf (actor-pos a) p)))

(defun sound-at (kind p &optional (gain 1.0))
  (when (and *native-ready* *player*)
    (let* ((delta (v- p (actor-pos *player*))) (distance (len delta))
           (right (v (cos (actor-yaw *player*)) 0 (- (sin (actor-yaw *player*))))))
      (when (< distance 55)
        (ss-sound kind (* *volume* gain (/ 1 (+ 1 (* 0.07 distance))))
                  (clamp (+ 0.5 (* 0.45 (dot3 (unit delta) right))) 0.05 0.95))))))
(defun notify (s &optional (seconds 1.5)) (setf *notice* s *notice-time* seconds))

(defun jump-body (a wish)
  (cond ((actor-ground a)
         (setf (v-y (actor-vel a)) 10.2 (actor-ground a) nil (actor-jump-buffer a) 0)
         (sound-at 4 (actor-pos a) 0.45))
        ((<= (actor-wall-cool a) 0)
         (let ((normal (wall-normal (actor-pos a))))
           (when normal
             (let ((push (v+ (v* normal 16) (v* wish 4))))
               (setf (v-x (actor-vel a)) (v-x push) (v-z (actor-vel a)) (v-z push)
                     (v-y (actor-vel a)) 11.5 (actor-wall-cool a) 0.24 (actor-jump-buffer a) 0)
               (incf (actor-wall-kicks a))
               (when (eq a *player*) (setf *kick-flash* 0.4) (notify "WALL KICK  //  MOMENTUM BOOST" 0.7))
               (sound-at 5 (actor-pos a) 0.75)))))))

(defun accelerate (a wish dt)
  (let* ((velocity (actor-vel a)) (speed (len (flat velocity))) (ground (actor-ground a)))
    (when (and ground (<= (actor-jump-buffer a) 0))
      (let ((scale (if (< speed 0.01) 0 (/ (max 0 (- speed (* (max speed 4) 6 dt))) speed))))
        (setf (v-x velocity) (* (v-x velocity) scale) (v-z velocity) (* (v-z velocity) scale))))
    (let* ((current (dot3 (flat velocity) wish))
           (add (min (max 0 (- 12 current)) (* (if ground 95 22) dt))))
      (incf (v-x velocity) (* (v-x wish) add)) (incf (v-z velocity) (* (v-z wish) add)))
    (let ((horizontal (len (flat velocity))))
      (when (> horizontal 32)
        (setf (v-x velocity) (* (v-x velocity) (/ 32 horizontal)) (v-z velocity) (* (v-z velocity) (/ 32 horizontal)))))
    (when (> (actor-jump-buffer a) 0) (jump-body a wish))
    (decf (v-y velocity) (* 28 dt))
    (move-body a dt)
    (incf (actor-walk a) (* speed dt 1.5))
    (dolist (pad *pads*)
      (when (and (< (actor-pad-cool a) 0.01) (< (len (flat (v- (actor-pos a) pad))) 1.5)
                 (< (v-y (actor-pos a)) 0.4))
        (setf (v-y velocity) 21 (actor-ground a) nil (actor-pad-cool a) 1)
        (sound-at 5 pad 0.9)
        (when (eq a *player*) (notify "LAUNCH PAD" 0.8))))))

(defun ray-box (origin dir b)
  (let ((lo (box-min b)) (hi (box-max b)) (near 0.0) (far 1000.0))
    (loop for o in (list (v-x origin) (v-y origin) (v-z origin))
          for d in (list (v-x dir) (v-y dir) (v-z dir))
          for low in (list (v-x lo) (v-y lo) (v-z lo))
          for high in (list (v-x hi) (v-y hi) (v-z hi)) do
      (if (< (abs d) 0.000001)
          (unless (<= low o high) (return-from ray-box nil))
          (let ((a (/ (- low o) d)) (c (/ (- high o) d)))
            (setf near (max near (min a c)) far (min far (max a c)))
            (when (> near far) (return-from ray-box nil)))))
    (when (>= far 0) near)))
(defun wall-distance (origin dir &optional (limit 100.0))
  (let ((result limit))
    (dolist (b *blocks*) (let ((d (ray-box origin dir b))) (when d (setf result (min result d)))))
    (when (< (v-y dir) -0.0001) (setf result (min result (/ (- (v-y origin)) (v-y dir)))))
    result))
(defun eye (a) (v+ (actor-pos a) (v 0 1.56 0)))
(defun visible (a b)
  (let* ((origin (eye a)) (delta (v- (v+ (actor-pos b) (v 0 1.0 0)) origin)) (d (len delta)))
    (> (wall-distance origin (unit delta) d) (- d 0.1))))
(defun ray-actor (origin dir a)
  (let* ((p (actor-pos a))
         (box (make-block :pos (v+ p (v 0 0.88 0)) :size (v 0.84 1.76 0.84))))
    (ray-box origin dir box)))

(defun add-beam (from to color &optional (radius 0.025) (life 0.1))
  (push (make-effect :from from :to to :color color :radius radius :life life :max-life life) *effects*))
(defun sparks (p color &optional (count 9))
  (dotimes (i count)
    (push (make-effect :from p :to (v+ p (v (rnd -1 1) (rnd -0.5 1) (rnd -1 1)))
                       :color color :kind :spark :life 0.25 :max-life 0.25 :radius 0.04) *effects*)))
(defun spawn-actor (a)
  (let ((best (first *spawns*)) (score -1.0))
    (dolist (p (sort (copy-list *spawns*) #'< :key (lambda (p) (declare (ignore p)) (random 1.0))))
      (let ((d (reduce #'min *actors* :initial-value 100.0
                       :key (lambda (other) (if (or (eq a other) (> (actor-dead other) 0)) 100.0 (distance3 p (actor-pos other)))))))
        (when (> d score) (setf score d best p))))
    (setf (actor-pos a) (v+ best (v 0 0.04 0)) (actor-vel a) (v 0 0 0)
          (actor-hp a) 100 (actor-armor a) 25 (actor-dead a) 0 (actor-invuln a) 1.8
          (actor-ammo a) (vector 180 24 16 16) (actor-cool a) 0 (actor-ground a) nil
          (actor-yaw a) (angle-to best (v 0 (v-y best) 0)) (actor-pitch a) 0
          (actor-path a) nil (actor-think a) 0 (actor-goal a) nil (actor-target a) nil
          (actor-dash-cool a) 0 (actor-wall-cool a) 0 (actor-jump-buffer a) 0)))
(defun start-match ()
  (setf *time* 0.0f0 *match-left* 300.0f0 *feed* nil *rockets* nil *effects* nil
        *damage-flash* 0 *hit-flash* 0 *kick-flash* 0)
  (make-arena)
  (setf *player* (make-actor :name "YOU" :color #x4AE5DAFF :pos (v 0 0 0))
        *actors* (list *player*))
  (dotimes (i *bot-count*)
    (setf *actors* (append *actors* (list (make-actor :name (aref *bot-names* i) :color (aref *bot-colors* i) :bot t :pos (v 0 0 0))))))
  (dolist (a *actors*) (spawn-actor a))
  (setf *state* :playing)
  (when *native-ready* (ss-capture 1))
  (notify (format nil "FRAG LIMIT ~D  //  FIVE MINUTES  //  GOOD HUNTING" *frag-limit*) 3))

(defun hurt (victim amount attacker &optional impulse)
  (when (and (<= (actor-dead victim) 0) (<= (actor-invuln victim) 0))
    (let* ((absorb (min (actor-armor victim) (round (* amount 0.6)))) (damage (- amount absorb)))
      (decf (actor-armor victim) absorb) (decf (actor-hp victim) damage)
      (when impulse (setf (actor-vel victim) (v+ (actor-vel victim) impulse)))
      (when (eq victim *player*) (setf *damage-flash* 0.45) (sound-at 7 (actor-pos victim) 0.6))
      (when (and attacker (not (eq attacker victim)))
        (incf (actor-hits attacker))
        (when (eq attacker *player*) (setf *hit-flash* 0.12) (sound-at 6 (actor-pos attacker) 0.25)))
      (when (<= (actor-hp victim) 0)
        (incf (actor-deaths victim))
        (setf (actor-dead victim) 2.0 (actor-vel victim) (v 0 0 0))
        (if (and attacker (not (eq attacker victim)))
            (progn (incf (actor-frags attacker)) (incf (actor-kills attacker)))
            (decf (actor-frags victim)))
        (push (list (format nil "~A  >  ~A" (if attacker (actor-name attacker) "ARENA") (actor-name victim))
                    (+ *time* 5) (if attacker (actor-color attacker) #xFFFFFFFF)) *feed*)
        (sparks (v+ (actor-pos victim) (v 0 0.8 0)) (actor-color victim) 18)
        (sound-at 3 (actor-pos victim) 0.4)
        (when (and attacker (eq attacker *player*) (not (eq victim attacker)))
          (notify (format nil "FRAGGED ~A" (actor-name victim)) 1.2))))))

(defun hitscan (a dir damage color &optional (radius 0.02) (life 0.08))
  (let* ((origin (eye a)) (nearest (wall-distance origin dir)) (victim nil))
    (dolist (b *actors*)
      (unless (or (eq a b) (> (actor-dead b) 0))
        (let ((d (ray-actor origin dir b))) (when (and d (< d nearest)) (setf nearest d victim b)))))
    (let ((end (v+ origin (v* dir nearest)))
          (muzzle (v+ origin (v+ (v* dir 0.75) (v (* 0.25 (cos (actor-yaw a))) -0.18 (* -0.25 (sin (actor-yaw a))))))))
      (add-beam muzzle end color radius life)
      (when victim (hurt victim damage a) (sparks end color 3)))))
(defun shoot (a &optional aim)
  (let* ((weapon (actor-weapon a)) (ammo (actor-ammo a)))
    (when (and (<= (actor-cool a) 0) (<= (actor-dead a) 0) (> (aref ammo weapon) 0))
      (decf (aref ammo weapon)) (incf (actor-shots a))
      (setf (actor-invuln a) 0 (actor-recoil a) 1.0)
      (let ((dir (or aim (direction (actor-yaw a) (actor-pitch a)))) (color (aref *weapon-colors* weapon)))
        (case weapon
          (0 (setf (actor-cool a) 0.105) (hitscan a (unit (v+ dir (v (rnd -0.008 0.008) (rnd -0.008 0.008) (rnd -0.008 0.008)))) 10 color))
          (1 (setf (actor-cool a) 0.78)
             (dotimes (i 11) (hitscan a (unit (v+ dir (v (rnd -0.07 0.07) (rnd -0.07 0.07) (rnd -0.07 0.07)))) 9 color 0.015 0.09)))
          (2 (setf (actor-cool a) 0.7)
             (push (make-rocket :pos (v+ (eye a) (v* dir 0.8)) :vel (v* dir 34) :owner a) *rockets*))
          (3 (setf (actor-cool a) 1.15) (hitscan a dir 90 color 0.045 0.25)))
        (sound-at (case weapon (0 0) (1 1) (2 1) (3 2)) (actor-pos a) (if (= weapon 0) 0.55 1))))))
(defun explode (r)
  (let ((p (rocket-pos r)) (owner (rocket-owner r)))
    (push (make-effect :from p :to p :color #xFF984DFF :life 0.45 :max-life 0.45 :radius 4.5 :kind :blast) *effects*)
    (sparks p #xFFBA65FF 16) (sound-at 3 p 1)
    (dolist (a *actors*)
      (let* ((center (v+ (actor-pos a) (v 0 0.85 0))) (delta (v- center p)) (d (len delta)))
        (when (and (< d 4.8) (<= (actor-dead a) 0)
                   (> (wall-distance (v+ p (v* (unit delta) 0.08)) (unit delta) d) (- d 0.15)))
          (let* ((scale (- 1 (/ d 4.8))) (self (eq a owner))
                 (impulse (v* (unit (v+ delta (v 0 0.9 0))) (* (if self 26 17) scale))))
            ;; Spawn protection blocks damage, but must not block rocket-jump impulse.
            (if (and self (> (actor-invuln a) 0))
                (setf (actor-vel a) (v+ (actor-vel a) impulse))
                (hurt a (round (* (if self 45 115) scale)) owner impulse))))))))

(defun update-rockets (dt)
  (setf *rockets*
        (delete-if (lambda (r)
                     (decf (rocket-life r) dt)
                     (let* ((old (rocket-pos r)) (travel (* dt (len (rocket-vel r))))
                            (dir (unit (rocket-vel r))) (wall (wall-distance old dir travel)) (hit nil))
                       (dolist (a *actors*)
                         (unless (or (eq a (rocket-owner r)) (> (actor-dead a) 0))
                           (let ((d (ray-actor old dir a))) (when (and d (< d wall)) (setf wall d hit t)))))
                       (setf (rocket-pos r) (v+ old (v* dir (max 0 (- wall 0.04)))))
                       (if (or hit (< wall travel) (<= (rocket-life r) 0))
                           (progn (explode r) t)
                           (progn (setf (rocket-pos r) (v+ old (v* dir travel))) nil)))) *rockets*)))

(defun collect-pickup (a item)
  (let ((kind (pickup-kind item)) (ammo (actor-ammo a)) (taken t))
    (case kind
      (:health (if (< (actor-hp a) 100) (setf (actor-hp a) (min 100 (+ (actor-hp a) 35))) (setf taken nil)))
      (:mega (if (< (actor-hp a) 175) (setf (actor-hp a) (min 175 (+ (actor-hp a) 75))) (setf taken nil)))
      (:armor (if (< (actor-armor a) 150) (setf (actor-armor a) (min 150 (+ (actor-armor a) 60))) (setf taken nil)))
      (:ammo (incf (aref ammo 0) 90))
      (:shells (incf (aref ammo 1) 12))
      (:rockets (incf (aref ammo 2) 10))
      (:rail (incf (aref ammo 3) 8)))
    (when taken
      (setf (pickup-timer item) (if (eq kind :mega) 30.0 18.0))
      (sound-at 8 (pickup-pos item) 0.6)
      (when (eq a *player*) (notify (format nil "+ ~A" (string-upcase (symbol-name kind))) 0.8)))))
(defun update-pickups (dt)
  (dolist (item *pickups*)
    (if (> (pickup-timer item) 0) (decf (pickup-timer item) dt)
        (dolist (a *actors*)
          (when (and (<= (pickup-timer item) 0) (<= (actor-dead a) 0)
                     (< (distance3 (v+ (actor-pos a) (v 0 0.45 0)) (pickup-pos item)) 1.35))
            (collect-pickup a item))))))

(defun choose-target (a)
  (let ((best nil) (distance 50.0))
    (dolist (b *actors* best)
      (let ((d (distance3 (actor-pos a) (actor-pos b))))
        (when (and (not (eq a b)) (<= (actor-dead b) 0) (< d distance) (visible a b))
          (setf best b distance d))))))
(defun choose-goal (a)
  (let ((best nil) (score -1000))
    (dolist (item *pickups*)
      (when (<= (pickup-timer item) 0)
        (let ((s (- (case (pickup-kind item)
                      ((:health :mega) (if (< (actor-hp a) 75) 55 8))
                      (:armor (if (< (actor-armor a) 40) 28 8))
                      (t 12))
                    (* 0.6 (distance3 (actor-pos a) (pickup-pos item))))))
          (when (> s score) (setf score s best (pickup-pos item))))))
    (if (and best (> score 2)) best (aref *nav* (random (length *nav*))))))
(defun update-bot (a dt)
  (decf (actor-think a) dt)
  (when (<= (actor-think a) 0)
    (setf (actor-think a) (rnd 0.3 0.65) (actor-target a) (choose-target a))
    (let ((goal (if (actor-target a) (actor-pos (actor-target a)) (choose-goal a))))
      (setf (actor-goal a) goal (actor-path a) (route (actor-pos a) goal))))
  (let* ((target (actor-target a))
         (live (and target (<= (actor-dead target) 0) (visible a target)))
         (path (actor-path a)) (p (actor-pos a))
         (goal (if path (car path) (or (actor-goal a) p)))
         (wish (unit (flat (v- goal p)))))
    (when (and path (< (len (flat (v- goal p))) 1.0)) (pop (actor-path a)))
    (when (or (> (v-y goal) (+ (v-y p) 0.5)) (> (actor-stuck a) 0.45))
      (setf (actor-jump-buffer a) 0.1))
    (if live
        (let* ((delta (v- (v+ (actor-pos target) (v 0 1.05 0)) (eye a))) (d (len delta))
               (desired (angle-to p (actor-pos target)))
               (turn (clamp (angle-delta desired (actor-yaw a)) (* -5 dt) (* 5 dt))))
          (incf (actor-yaw a) turn)
          (setf (actor-pitch a) (asin (clamp (/ (v-y delta) (max 0.01 d)) -1 1)))
          (when (< d 22)
            (let* ((toward (unit (flat delta))) (strafe (v (- (v-z toward)) 0 (v-x toward)))
                   (side (if (plusp (sin (+ (* *time* 1.9) (actor-color a)))) 1 -1)))
              (setf wish (unit (v+ (v* toward (if (< d 7) -0.7 0.4)) (v* strafe side))))))
          (let ((w (cond ((and (> d 16) (> (aref (actor-ammo a) 3) 0)) 3)
                         ((and (> d 9) (> (aref (actor-ammo a) 2) 0) (< (v-y (actor-pos target)) (+ (v-y p) 1.8))) 2)
                         ((and (< d 9) (> (aref (actor-ammo a) 1) 0)) 1) (t 0))))
            (setf (actor-weapon a) w)
            (when (< (abs (angle-delta desired (actor-yaw a))) 0.25)
              (let* ((error (aref #(0.10 0.047 0.016) *difficulty*))
                     (aim-point (if (= w 2) (v+ (actor-pos target) (v 0 0.15 0)) (v+ (actor-pos target) (v 0 1.1 0))))
                     (lead (if (= w 2) (v* (actor-vel target) (/ d 34)) (v 0 0 0)))
                     (aim (unit (v+ (unit (v- (v+ aim-point lead) (eye a))) (v (rnd (- error) error) (rnd (- error) error) (rnd (- error) error))))))
                (when (< (random 1.0) (aref #(0.65 0.82 1.0) *difficulty*)) (shoot a aim))))))
        (when (> (len wish) 0.1) (setf (actor-yaw a) (angle-to p goal) (actor-pitch a) 0)))
    (if (< (distance3 p (actor-last-pos a)) 0.006) (incf (actor-stuck a) dt) (setf (actor-stuck a) 0))
    (when (> (actor-stuck a) 1.4) (setf (actor-think a) 0 (actor-stuck a) 0))
    (setf (actor-last-pos a) (v (v-x p) (v-y p) (v-z p)))
    (accelerate a wish dt)))

(defun update-timers (a dt)
  (setf (actor-cool a) (max 0 (- (actor-cool a) dt))
        (actor-invuln a) (max 0 (- (actor-invuln a) dt))
        (actor-wall-cool a) (max 0 (- (actor-wall-cool a) dt))
        (actor-pad-cool a) (max 0 (- (actor-pad-cool a) dt))
        (actor-dash-cool a) (max 0 (- (actor-dash-cool a) dt))
        (actor-jump-buffer a) (max 0 (- (actor-jump-buffer a) dt))
        (actor-recoil a) (max 0 (- (actor-recoil a) (* dt 7)))))
(defun tick-game (dt wish fire jump-held)
  (incf *time* dt) (decf *match-left* dt)
  (dolist (a *actors*)
    (update-timers a dt)
    (if (> (actor-dead a) 0)
        (progn (setf (actor-dead a) (max 0 (- (actor-dead a) dt)))
               (when (zerop (actor-dead a)) (spawn-actor a)))
        (if (actor-bot a) (update-bot a dt)
            (progn (when (and jump-held (actor-ground a)) (setf (actor-jump-buffer a) 0.1))
                   (accelerate a wish dt) (when fire (shoot a))))))
  (update-rockets dt) (update-pickups dt)
  (dolist (fx *effects*) (decf (effect-life fx) dt))
  (setf *effects* (delete-if (lambda (fx) (<= (effect-life fx) 0)) *effects*)
        *feed* (remove-if (lambda (entry) (< (second entry) *time*)) *feed*)
        *hit-flash* (max 0 (- *hit-flash* dt)) *damage-flash* (max 0 (- *damage-flash* dt))
        *kick-flash* (max 0 (- *kick-flash* dt)) *notice-time* (max 0 (- *notice-time* dt)))
  (when (or (<= *match-left* 0) (some (lambda (a) (>= (actor-frags a) *frag-limit*)) *actors*))
    (setf *state* :results) (when *native-ready* (ss-capture 0) (sound-at 8 (actor-pos *player*) 0.8))))
