(in-package :slipstream)
(defun self-test ()
  (let ((*native-ready* nil) (*random-state* (sb-ext:seed-random-state 42))
        (*bot-count* 4) (*difficulty* 1) (*frag-limit* 10000) (*state* :menu))
    (flet ((check (condition name) (unless condition (error "FAILED: ~A" name)) (format t "PASS ~A~%" name)))
      (make-arena)
      (check (= (floor-at 0 0) 1.2) "three-dimensional floor heights")
      (check (> (length *nav*) 500) "navigation graph")
      (check (= (angle-to (v 1 0 1) (v 1 0 1)) 0) "overlapping actors have a defined aim angle")
      (check (route (v -20 0 -24) (v 22 3.2 7)) "bot route to elevated weapon pickup")
      (check (not (visible (make-actor :pos (v -12 0 -9)) (make-actor :pos (v -6 0 -9)))) "walls occlude bot vision")
      (let ((a (make-actor :pos (v -27.5 2 15) :vel (v -5 -2 0))))
        (jump-body a (v 0 0 -1))
        (check (and (> (v-x (actor-vel a)) 10) (> (v-y (actor-vel a)) 10) (= (actor-wall-kicks a) 1)) "airborne wall kick pushes away and upward")
        (dotimes (i 120) (accelerate a (v -1 0 0) +tick+))
        (check (>= (v-x (actor-pos a)) -27.59) "body cannot cross arena wall"))
      (let ((a (make-actor :pos (v 27 18 0) :vel (v 32 0 0))))
        (dotimes (i 30) (move-body a +tick+))
        (check (<= (v-x (actor-pos a)) 27.58) "rocket jumps cannot escape above perimeter"))
      (let ((a (make-actor :pos (v 0 0 -10) :ground t)))
        (dotimes (i 120) (accelerate a (v 0 0 -1) +tick+))
        (check (> (v-y (actor-pos a)) 0.3) "automatic stair climbing")
        (setf (actor-jump-buffer a) 0.12)
        (accelerate a (v 1 0 0) +tick+)
        (check (> (v-y (actor-vel a)) 9) "ground jump"))
      (start-match)
      (let ((a *player*) (b (second *actors*)))
        (setf (actor-pos a) (v -18 0 -24) (actor-pos b) (v -18 0 -20)
              (actor-invuln b) 0 (actor-invuln a) 0 (actor-armor b) 0)
        (hitscan a (v 0 0 1) 110 #xFFFFFFFF)
        (check (and (> (actor-dead b) 0) (= (actor-frags a) 1)) "hitscan damage, frag and death")
        (spawn-actor b)
        (check (and (= (actor-hp b) 100) (> (actor-invuln b) 0)) "respawn with shield")
        (setf (actor-pos a) (v -18 0 -24) (actor-vel a) (v 0 0 0))
        (explode (make-rocket :pos (v -18 0.1 -24) :vel (v 0 -34 0) :owner a))
        (check (> (v-y (actor-vel a)) 10) "rocket jump impulse")
        (let ((item (make-pickup :pos (v -4 0 -20) :kind :health)))
          (setf (actor-hp a) 40) (collect-pickup a item)
          (check (and (= (actor-hp a) 75) (> (pickup-timer item) 0)) "health pickup and respawn timer")))
      (start-match) (setf (actor-bot *player*) t)
      (let ((started (get-internal-real-time)))
        (dotimes (i 14400) (tick-game +tick+ (v 0 0 0) nil nil))
        (format t "SIMULATED 120 seconds in ~,2F seconds~%"
                (/ (- (get-internal-real-time) started) internal-time-units-per-second)))
      (check (> (reduce #'+ *actors* :key #'actor-kills) 12) "bots navigate, acquire targets and score frags autonomously")
      (check (every (lambda (a) (let ((p (actor-pos a)))
                                 (and (<= -28 (v-x p) 28) (<= -28 (v-z p) 28) (<= 0 (v-y p) 30)))) *actors*) "long simulation stays in arena bounds")
      (format t "BOT SCORES ~S~%" (mapcar (lambda (a) (list (actor-name a) (actor-frags a) (actor-deaths a))) *actors*))
    (format t "ALL GAMEPLAY CHECKS PASSED~%") t)))
