(in-package :slipstream)
(defun settings-path ()
  (merge-pathnames "Slipstream/settings.sexp" (pathname (concatenate 'string (or (sb-ext:posix-getenv "LOCALAPPDATA") (namestring (user-homedir-pathname))) "/"))))
(defun load-settings ()
  (when (probe-file (settings-path))
    (handler-case
        (with-open-file (s (settings-path))
          (let* ((*read-eval* nil) (data (read s nil nil)))
            (flet ((number-option (key default low high)
                     (let ((value (getf data key default))) (if (realp value) (clamp value low high) default))))
              (setf *sensitivity* (number-option :sensitivity 0.0022 0.0005 0.008)
                    *fov* (number-option :fov 90 75 115)
                    *volume* (number-option :volume 0.65 0 1)
                    *difficulty* (round (number-option :difficulty 1 0 2))
                    *bot-count* (round (number-option :bots 4 1 6))
                    *frag-limit* (round (number-option :frags 20 5 100))))))
      (error () nil))))
(defun save-settings ()
  (handler-case
      (progn (ensure-directories-exist (settings-path))
             (with-open-file (s (settings-path) :direction :output :if-exists :supersede)
               (write (list :sensitivity *sensitivity* :fov *fov* :volume *volume*
                            :difficulty *difficulty* :bots *bot-count* :frags *frag-limit*) :stream s)))
    (error () nil)))
(defun player-input (dt)
  (declare (ignore dt))
  (let* ((a *player*) (yaw (actor-yaw a))
         (forward (direction yaw 0)) (right (v (cos yaw) 0 (- (sin yaw))))
         (f (- (if (down 87) 1 0) (if (down 83) 1 0)))
         (s (- (if (down 68) 1 0) (if (down 65) 1 0)))
         (wish (unit (v+ (v* forward f) (v* right s)))))
    (setf (actor-yaw a) (mod (- yaw (* (ss-mx) *sensitivity*)) (* 2 pi))
          (actor-pitch a) (clamp (- (actor-pitch a) (* (ss-my) *sensitivity*)) -1.48 1.48))
    (when (pressed 32) (setf (actor-jump-buffer a) 0.13))
    (when (and (pressed 340) (<= (actor-dash-cool a) 0) (<= (actor-dead a) 0))
      (let ((d (if (> (len wish) 0) wish forward)))
        (incf (v-x (actor-vel a)) (* 13 (v-x d))) (incf (v-z (actor-vel a)) (* 13 (v-z d)))
        (setf (actor-dash-cool a) 1.25)
        (sound-at 5 (actor-pos a) 0.4)))
    (dotimes (i 4) (when (pressed (+ 49 i)) (setf (actor-weapon a) i)))
    (let ((wheel (ss-scroll)))
      (unless (zerop wheel) (setf (actor-weapon a) (mod (- (actor-weapon a) (signum (round wheel))) 4))))
    (values wish (plusp (ss-mouse 0)) (down 32))))

(defun main ()
  (let* ((args (cdr sb-ext:*posix-argv*))
         (smoke (member "--smoke-test" args :test #'string=))
         (demo (member "--demo" args :test #'string=))
         (root (make-pathname :name nil :type nil :defaults sb-ext:*runtime-pathname*))
         (dll (merge-pathnames "arena.dll" root))
         (accumulator 0.0f0) (frames 0) (total-frame-time 0.0))
    (when (member "--self-test" args :test #'string=) (self-test) (return-from main 0))
    (unless (probe-file dll) (setf dll (merge-pathnames "dist/Slipstream/arena.dll" *default-pathname-defaults*)))
    (handler-case
      (handler-bind ((error (lambda (e)
                             (with-open-file (s (merge-pathnames "crash.log" root) :direction :output :if-exists :supersede)
                               (format s "SLIPSTREAM error: ~A~%" e)
                               (sb-debug:print-backtrace :stream s :count 35)))))
        (progn
          (sb-alien:load-shared-object (namestring dll))
          (ss-init 1440 810) (setf *native-ready* t *state* :menu *exit-request* nil *help* nil *menu-time* 0)
          (unless smoke (load-settings))
          (setf *actors* nil *player* nil *rockets* nil *effects* nil *time* 0)
          (make-arena)
          (when demo (start-match) (setf (actor-bot *player*) t) (ss-capture 0))
          (unwind-protect
               (loop until (or *exit-request* (plusp (ss-quit))) do
                 (let ((dt (min 0.1 (ss-dt))))
                   (incf frames) (incf total-frame-time dt) (incf *menu-time* dt)
                   (ss-input)
                   (when (pressed 300) (ss-fullscreen))
                   (when (pressed 290)
                     (setf *help* (not *help*))
                     (when (eq *state* :playing) (setf *state* :paused) (ss-capture 0)))
                   (when (pressed 256)
                     (cond (*help* (setf *help* nil))
                           ((eq *state* :playing) (setf *state* :paused) (ss-capture 0))
                           ((eq *state* :paused) (setf *state* :playing) (ss-capture 1))
                           ((eq *state* :menu) (setf *exit-request* t))
                           (t (setf *state* :menu))))
                   (when (and (eq *state* :playing) (zerop (ss-focus)) (not smoke) (not demo))
                     (setf *state* :paused) (ss-capture 0))
                   (when (member *state* '(:menu :paused)) (menu-input))
                   (when smoke
                     (case frames
                       (35 (ss-shot "artifacts/menu.png"))
                       (40 (start-match) (setf (actor-bot *player*) t) (ss-capture 0))
                       (190 (ss-shot "artifacts/gameplay.png"))
                       (245 (setf *state* :paused))
                       (250 (ss-shot "artifacts/pause.png"))
                       (255 (setf *state* :results))
                       (265 (ss-shot "artifacts/results.png"))
                       (270 (setf *exit-request* t))))
                   (when (eq *state* :playing)
                     (multiple-value-bind (wish fire jump) (if (or smoke demo) (values (v 0 0 0) nil nil) (player-input dt))
                       (incf accumulator dt)
                       (loop while (and (>= accumulator +tick+) (eq *state* :playing)) do
                         (tick-game +tick+ wish fire jump) (decf accumulator +tick+))))
                   (unless (eq *state* :playing) (setf accumulator 0.0f0))
                   (render-frame)))
            (ss-capture 0) (unless smoke (save-settings))
            (when smoke
              (with-open-file (s "artifacts/render-check.sexp" :direction :output :if-exists :supersede)
                (write (list :frames frames :average-fps (/ frames (max total-frame-time 0.01))
                             :audio-ready (ss-audio) :bots (length *actors*)
                             :frags (mapcar (lambda (a) (list (actor-name a) (actor-frags a))) *actors*)) :stream s)))
            (ss-close) (setf *native-ready* nil))))
      (error (e)
        (declare (ignore e))
        (when *native-ready* (ss-capture 0) (ss-close))
        (sb-ext:exit :code 1)))
    (sb-ext:exit :code 0)))
