(defpackage :slipstream (:use :cl) (:export :main :self-test))
(in-package :slipstream)
(declaim (optimize (speed 2) (safety 2) (debug 1)))

(defmacro native (name result &rest args)
  (let ((raw (intern (concatenate 'string "%" (symbol-name name))))
        (types '((float . sb-alien:single-float) (int . sb-alien:int)
                 (uint . sb-alien:unsigned-int) (string . sb-alien:c-string)
                 (void . sb-alien:void))))
    `(progn
       (sb-alien:define-alien-routine
           (,(substitute #\_ #\- (string-downcase (symbol-name name))) ,raw)
           ,(cdr (assoc result types))
         ,@(mapcar (lambda (a) `(,(car a) ,(cdr (assoc (cadr a) types)))) args))
       (defun ,name ,(mapcar #'car args)
         ;; Native graphics/audio code follows the usual C IEEE-754 policy.
         (sb-int:with-float-traps-masked (:divide-by-zero :invalid :overflow)
         (,raw ,@(mapcar (lambda (a)
                          (case (cadr a)
                            (float `(float ,(car a) 1.0f0))
                            (int `(round ,(car a)))
                            (t (car a)))) args)))))))

(native ss-init void (w int) (h int))
(native ss-close void)
(native ss-quit int)
(native ss-focus int)
(native ss-width int)
(native ss-height int)
(native ss-dt float)
(native ss-fps int)
(native ss-input void)
(native ss-key int (key int))
(native ss-press int (key int))
(native ss-mouse int (key int))
(native ss-click int (key int))
(native ss-mx float)
(native ss-my float)
(native ss-scroll float)
(native ss-cursor-x int)
(native ss-cursor-y int)
(native ss-capture void (yes int))
(native ss-fullscreen void)
(native ss-begin void)
(native ss-end void)
(native ss-camera void (x float) (y float) (z float) (dx float) (dy float) (dz float) (fov float) (roll float))
(native ss-2d void)
(native ss-box void (x float) (y float) (z float) (w float) (h float) (d float) (c uint))
(native ss-glow void (x float) (y float) (z float) (w float) (h float) (d float) (c uint))
(native ss-wire void (x float) (y float) (z float) (w float) (h float) (d float) (c uint))
(native ss-sphere void (x float) (y float) (z float) (r float) (c uint))
(native ss-ring void (x float) (y float) (z float) (r float) (c uint))
(native ss-beam void (x float) (y float) (z float) (bx float) (by float) (bz float) (r float) (c uint))
(native ss-bot void (x float) (y float) (z float) (yaw float) (c uint) (walk float) (weapon int))
(native ss-weapon void (kind int) (bob float) (recoil float))
(native ss-rect void (x int) (y int) (w int) (h int) (c uint))
(native ss-gradient void (x int) (y int) (w int) (h int) (a uint) (b uint))
(native ss-line void (x int) (y int) (bx int) (by int) (c uint))
(native ss-circle void (x int) (y int) (r float) (c uint))
(native ss-text void (s string) (x int) (y int) (size int) (c uint))
(native ss-measure int (s string) (size int))
(native ss-sound void (kind int) (volume float) (pan float))
(native ss-audio int)
(native ss-shot void (path string))

(defvar *native-ready* nil)
(defvar *volume* 0.65f0)
(defun down (key) (plusp (ss-key key)))
(defun pressed (key) (plusp (ss-press key)))
