; Integration stages. Build game/build.ps1 before launching.
; sbcl --script workshop/run-stage.lisp map|movement|combat|full
; --smoke closes after 180 frames and captures a screenshot for verification.
(load (merge-pathnames "../game/platform.lisp" *load-truename*))
(load (merge-pathnames "../game/arena.lisp" *load-truename*))
(load (merge-pathnames "../game/view.lisp" *load-truename*))
(load (merge-pathnames "../game/checks.lisp" *load-truename*))
(load (merge-pathnames "../game/main.lisp" *load-truename*))
(in-package :slipstream)
(let* ((args sb-ext:*posix-argv*)
       (stage (or (find-if (lambda (x) (member x '("map" "movement" "combat" "full") :test #'string=)) args) "map"))
       (smoke (member "--smoke" args :test #'string=))
       (root (merge-pathnames "../game/" *load-truename*))
       (dll (merge-pathnames "dist/Slipstream/arena.dll" root))
       (target nil) (frames 0) (accumulator 0.0))
  (setf *default-pathname-defaults* (make-pathname :name nil :type nil :defaults root))
  (when (string= stage "full") (main) (sb-ext:exit))
  (unless (probe-file dll) (error "Build game/build.ps1 first. Missing ~A" dll))
  (sb-alien:load-shared-object (namestring dll))
  (ss-init 1280 720)
  (setf *native-ready* t *bot-count* 0)
  (start-match)
  (setf (actor-pos *player*) (v -5 0 15) (actor-yaw *player*) 0)
  (when (string= stage "combat")
    (setf target (make-actor :name "TARGET" :color #xFF785FFF :pos (v -5 0 8))
          *actors* (list *player* target)))
  (ss-capture (if (or smoke (string= stage "map")) 0 1))
  (unwind-protect
       (loop until (or (plusp (ss-quit)) (and smoke (>= frames 180))) do
         (incf frames)
         (ss-input)
         (when (pressed 256) (return))
         (let ((dt (min 0.1 (ss-dt))))
           (unless (string= stage "map")
             (multiple-value-bind (wish fire held) (if smoke (values (v 0 0 0) (string= stage "combat") nil) (player-input dt))
               (declare (ignore held))
               (incf accumulator dt)
               (loop while (>= accumulator +tick+) do
                 (incf *time* +tick+)
                 (dolist (a *actors*)
                   (update-timers a +tick+)
                   (when (> (actor-dead a) 0)
                     (setf (actor-dead a) (max 0 (- (actor-dead a) +tick+)))
                     (when (zerop (actor-dead a)) (spawn-actor a))))
                 (when target (setf (actor-pos target) (v -5 0 8) (actor-vel target) (v 0 0 0)))
                 (when (<= (actor-dead *player*) 0)
                   (accelerate *player* wish +tick+)
                   (when (and fire (string= stage "combat")) (shoot *player*)))
                 (update-rockets +tick+) (update-pickups +tick+)
                 (setf *effects* (delete-if (lambda (e) (decf (effect-life e) +tick+) (<= (effect-life e) 0)) *effects*))
                 (decf accumulator +tick+)))))
         (if (string= stage "map")
             (progn (ss-begin) (ss-camera 0 30 35 0 -25 -35 65 0)
                    (ss-box 0 -0.35 0 60 0.7 60 #x424F60FF)
                    (dolist (b *blocks*) (box3 (block-pos b) (block-size b) (block-color b)))
                    (ss-2d)
                    (ss-text "LISP ATELIER / MAP STAGE / ESC TO CLOSE" 30 30 20 #xD4C18FFF)
                    (ss-end))
             (let* ((p (eye *player*)) (d (direction (actor-yaw *player*) (actor-pitch *player*))))
               (ss-begin)
               (ss-camera (v-x p) (v-y p) (v-z p) (v-x d) (v-y d) (v-z d) 90 0)
               (render-arena)
               (when (string= stage "combat") (ss-weapon (actor-weapon *player*) 0 (actor-recoil *player*)))
               (ss-2d)
               (ss-text (if (string= stage "combat")
                            "COMBAT / WASD, SPACE, SHIFT, MOUSE, 1-4 / ESC TO CLOSE"
                            "MOVEMENT / WASD, SPACE: JUMP + WALL KICK, SHIFT: DASH / ESC TO CLOSE")
                        28 28 16 #xD4C18FFF)
               (ss-text (format nil "HP ~D / ARMOR ~D / FRAGS ~D / WALL KICKS ~D"
                                (actor-hp *player*) (actor-armor *player*) (actor-frags *player*) (actor-wall-kicks *player*))
                        28 660 20 #xDDE8DCFF)
               (when (string= stage "combat")
                 (ss-line 630 360 650 360 #xDDE8DCFF) (ss-line 640 350 640 370 #xDDE8DCFF))
               (ss-end)))
         (when (and smoke (= frames (if target 50 170)))
           (ss-shot (namestring (merge-pathnames (concatenate 'string "artifacts/workshop-" stage ".png") root)))))
    (ss-capture 0) (setf *native-ready* nil) (ss-close))
  (when (and smoke target) (assert (> (actor-frags *player*) 0))
    (format t "PASS combat stage: stationary target hit, killed, and scored.~%")))
