; Loaded by workshop/09-native-window.lisp after the declaration checks.
(in-package :slipstream)
(let ((dll (merge-pathnames "../game/dist/Slipstream/arena.dll" *load-truename*)))
  (unless (probe-file dll) (error "Build game/build.ps1 first. Missing ~A" dll))
  (sb-alien:load-shared-object (namestring dll)))
(ss-init 960 540)
(setf *native-ready* t)
(let ((smoke (member "--smoke" sb-ext:*posix-argv* :test #'string=)) (frames 0))
(unwind-protect
     (loop until (or (plusp (ss-quit)) (and smoke (>= frames 180))) do
       (incf frames)
       (ss-input)
       (when (pressed 256) (return))
       (ss-begin)
       (ss-camera 5 4 7 -5 -3 -7 60 0)
       (ss-box 0 0.5 0 2 1 2 #x8DAD88FF)
       (ss-2d)
       (ss-text "LISP ATELIER / YOUR FIRST NATIVE WINDOW" 30 30 20 #xD4C18FFF)
       (ss-text "Edit ss-box dimensions, rerun. ESC to close." 30 480 18 #xDDE8DCFF)
       (ss-end)
       (when (and smoke (= frames 170))
         (ss-shot (namestring (merge-pathnames "../game/artifacts/workshop-window.png" *load-truename*)))))
  (setf *native-ready* nil)
  (ss-close)))
