import {readFile,writeFile,mkdir,readdir,copyFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import {chapters as first,parts,type Lang} from '../src/content.ts';
import {engineChapters} from '../src/engine.ts';
import {masteryChapters,glossary,references} from '../src/mastery.ts';
export const chapters=[...first,...engineChapters,...masteryChapters];
export const esc=(x:string)=>x.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const repo='https://github.com/dikmri/slipstream-lisp-textbook';
export function forms(text:string){
  const result:{name:string;code:string;line:number}[]=[];
  let depth=0,start=0,string=false,comment=false,escape=false,line=1,startLine=1;
  for(let i=0;i<text.length;i++){
    const c=text[i];
    if(c==='\n'){line++;comment=false;}
    if(comment)continue;
    if(string){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')string=false;continue;}
    if(c===';'){comment=true;continue;} if(c==='"'){string=true;continue;}
    if(c==='('){if(!depth){start=i;startLine=line;}depth++;}
    if(c===')'&&--depth===0){const code=text.slice(start,i+1);const m=code.match(/^\(def(?:un|macro|parameter|var|constant)\s+([^\s()]+)/i);if(m)result.push({name:m[1],code,line:startLine});}
  }
  return result;
}
export const files=['platform.lisp','arena.lisp','view.lisp','main.lisp','checks.lisp','build.lisp','build.ps1','run.lisp','play.cmd','native/bridge.c'];
const raw=Object.fromEntries(await Promise.all(files.map(async f=>[f,await readFile(new URL('../game/'+f,import.meta.url),'utf8')])));
export const sources=raw;
// Tokenize before escaping so quoted Lisp strings never become HTML.
function highlight(text:string){return text.split('\n').map(line=>{
  const re=/;[^\n]*|"(?:\\.|[^"\\])*"|\b(?:defun|defmacro|defstruct|let\*?|setf|if|when|unless|cond|loop|lambda|assert|defvar|defparameter|in-package|multiple-value-bind|values|quote|progn|handler-case|unwind-protect)\b|(?<![\w-]):[\w-]+|(?<![\w-])-?\d+(?:\.\d+)?(?:f\d+)?/g;
  let out='',pos=0;for(const m of line.matchAll(re)){out+=esc(line.slice(pos,m.index));const t=m[0];out+=`<span class="${t[0]===';'?'comment':t[0]==='"'?'string':/^[-\d]/.test(t)?'number':'keyword'}">${esc(t)}</span>`;pos=m.index!+t.length;}out+=esc(line.slice(pos));return `<span class="code-line">${out||' '}</span>`;
}).join('\n');}
const block=(text:string,label='COMMON LISP',lang:Lang='ja')=>`<div class="code-block"><div class="code-cap"><span>${esc(label)}</span><button type="button" class="copy-code">${lang==='ja'?'コピー':'Copy'}</button></div><pre tabindex="0"><code>${highlight(text)}</code></pre></div>`;
function lessonCode(text:string,lang:Lang){
  const marker='\n\n; Inside SBCL, not in PowerShell:\n';
  if(text.includes(marker)){const [shell,lisp]=text.split(marker);return block(shell,'POWERSHELL',lang)+block(lisp,'SBCL REPL',lang);}
  return block(text,/^(?:#(?![x(])|git |sbcl |cd |gcc |rg |\.\\)/.test(text)?'POWERSHELL / TERMINAL':'COMMON LISP / WORKBENCH',lang);
}
const sourcePanel=(c:typeof chapters[number],lang:Lang)=>c.sources.map(({file,names})=>{
  if(!raw[file])throw Error('Missing source '+file);
  const found=names.length?names.map(name=>{const f=forms(raw[file]).find(f=>f.name===name);if(!f)throw Error(`Missing ${file}: ${name}`);return f;}):[{name:file,code:raw[file],line:1}];
  return found.map(f=>`<details class="source-detail"><summary><span>${esc(file)}</span><strong>${esc(f.name)}</strong><small>L${f.line} ↗</small></summary><div class="source-body"><p><a href="${repo}/blob/main/game/${file}#L${f.line}" target="_blank" rel="noopener">${lang==='ja'?'GitHubでこの箇所を読む':'Read this location on GitHub'} ↗</a></p>${block(f.code,'SOURCE · '+file,lang)}</div></details>`).join('');
}).join('');
const names={ja:{toc:'目次',search:'章・用語を検索',goals:'この章で身につくこと',exercise:'あなたの手で、書く',hint:'手がかり',solution:'解答と考え方',quiz:'理解を確かめる',answer:'答えを確認',complete:'学習済みにする',completed:'学習済み',source:'実装の現場',workshop:'SBCLで確かめる',download:'教材をダウンロード',glossary:'用語集',sources:'ソース索引',previous:'前の章',next:'次の章',time:'分',progress:'学習進捗',lab:'実験室',close:'閉じる',references:'学びを続けるための一次資料'},en:{toc:'Contents',search:'Find a chapter or term',goals:'What you will learn',exercise:'Write it with your own hands',hint:'A hint',solution:'Solution & reasoning',quiz:'Check your understanding',answer:'Check answer',complete:'Mark as learned',completed:'Learned',source:'Inside the implementation',workshop:'Verify with SBCL',download:'Download the course',glossary:'Glossary',sources:'Source index',previous:'Previous',next:'Next',time:'min',progress:'Learning progress',lab:'Laboratory',close:'Close',references:'Primary references for your next step'}};
const num=(i:number)=>String(i).padStart(2,'0');
await mkdir(new URL('../public/en/',import.meta.url),{recursive:true});
for(const lang of ['ja','en'] as const){
  const t=names[lang],base=lang==='ja'?'./':'../';
  const links=parts.map((p,pi)=>`<div class="toc-group"><p>${p[lang]}</p>${chapters.map((c,i)=>c.part!==pi?'':`<a class="chapter-link" href="#${c.id}" data-id="${c.id}" data-search="${esc(c.title[lang]+' '+c.title[lang==='ja'?'en':'ja']+' '+c.id)}"><span>${num(i)}</span><strong>${esc(c.title[lang])}</strong><i aria-label="${t.completed}"></i></a>`).join('')}</div>`).join('');
  const articles=chapters.map((c,i)=>`<article id="${c.id}" class="chapter" data-index="${i}" aria-labelledby="title-${c.id}">
    <header class="chapter-head"><p class="eyebrow">${esc(parts[c.part][lang])} <span>${c.minutes} ${t.time}</span></p><div class="chapter-title"><span class="chapter-number">${num(i)}</span><h1 id="title-${c.id}">${esc(c.title[lang])}</h1></div><p class="subtitle">${esc(c.subtitle[lang])}</p></header>
    ${i===0?`<figure class="cover-art"><img src="${base}assets/foundry.png" alt="${lang==='ja'?'教材で再構築するSLIPSTREAMの立体アリーナとbot戦':'The three-dimensional SLIPSTREAM arena and bot battle you will reconstruct'}" width="1440" height="810"><figcaption><span>THE FINISHED WORK</span><span>SLIPSTREAM · COMMON LISP / RAYLIB</span></figcaption><div class="folio-mark" aria-hidden="true">( begin<br>&nbsp; :with-curiosity )</div></figure><div class="book-note"><span class="seal">λ</span><div><strong>${lang==='ja'?'動くものから、理解する人へ。':'From a working game to a mind that understands it.'}</strong><p>${lang==='ja'?'24章 · 8つの実験室 · 2言語 · 実際のFPSソースを同梱':'24 chapters · 8 laboratories · 2 languages · the complete FPS source'}</p></div></div>`:''}
    <aside class="goals"><p class="eyebrow">${t.goals}</p><ol>${c.goals.map(g=>`<li>${esc(g[lang])}</li>`).join('')}</ol></aside>
    ${c.sections.map((s,si)=>`<section class="lesson-section"><div class="section-label">${num(si+1)} / NOTES</div><h2>${esc(s.title[lang])}</h2>${s.paragraphs.map(p=>`<p>${esc(p[lang])}</p>`).join('')}${s.code?lessonCode(s.code,lang):''}${s.lab?`<div class="lab" data-lab="${s.lab}"><div class="lab-heading"><span class="eyebrow">${t.lab} / ${s.lab.toUpperCase()}</span><span class="lab-dot"></span></div><div class="lab-content"></div><noscript><p>${lang==='ja'?'実験室を動かすにはJavaScriptを有効にしてください。本文とソースはそのまま読めます。':'Enable JavaScript to use this lab. The text and source remain readable.'}</p></noscript></div>`:''}</section>`).join('')}
    <section class="workshop-panel"><p class="eyebrow">${t.workshop}</p><p>${lang==='ja'?'取得したリポジトリの最上位から実行します。表示がPASSになったら、数値や条件を一つ変えて予測と比較してください。':'Run from the downloaded repository root. After PASS, change one value or condition and compare with your prediction.'}</p>${block(`sbcl --script workshop/${num(i)}-${c.id}.lisp`,'POWERSHELL / TERMINAL',lang)}<a href="${base}workshop/${num(i)}-${c.id}.lisp" download>${lang==='ja'?'この章の演習ファイル':'Download this chapter’s workshop'} ↓</a></section>
    <section class="exercise"><p class="eyebrow">EXERCISE ${num(i)}</p><h2>${t.exercise}</h2><p>${esc(c.exercise.task[lang])}</p><details><summary>${t.hint}</summary><p>${esc(c.exercise.hint[lang])}</p></details><details><summary>${t.solution}</summary>${block(c.exercise.solution,'ONE POSSIBLE SOLUTION',lang)}<p>${esc(c.exercise.explanation[lang])}</p></details></section>
    <section class="implementation"><p class="eyebrow">${t.source}</p><p class="small-note">${lang==='ja'?'下のコードは同梱FPSから直接抜き出したものです。章の短い例と、実装の境界を照らし合わせてください。':'These excerpts come directly from the included FPS. Compare a chapter’s short example with the boundaries in the implementation.'}</p>${sourcePanel(c,lang)}</section>
    <form class="quiz" data-correct="${c.quiz.correct}"><p class="eyebrow">${t.quiz}</p><fieldset><legend>${esc(c.quiz.question[lang])}</legend>${c.quiz.options.map((o,oi)=>`<label><input type="radio" name="quiz-${c.id}" value="${oi}" required><span>${esc(o[lang])}</span></label>`).join('')}</fieldset><button class="primary" type="submit">${t.answer} ↗</button><div class="quiz-result" role="status" hidden><strong></strong><p>${esc(c.quiz.explanation[lang])}</p></div></form>
    <footer class="chapter-footer"><button class="complete-button" data-complete="${c.id}" data-default="${t.complete}" data-done="${t.completed}" type="button" aria-pressed="false">${t.complete} ✓</button><nav class="page-turn" aria-label="${lang==='ja'?'章の移動':'Chapter navigation'}">${i?`<a href="#${chapters[i-1].id}"><small>← ${t.previous}</small><span>${esc(chapters[i-1].title[lang])}</span></a>`:'<span></span>'}${i<23?`<a href="#${chapters[i+1].id}"><small>${t.next} →</small><span>${esc(chapters[i+1].title[lang])}</span></a>`:'<a href="#orientation"><small>↺ ATELIER</small><span>'+ (lang==='ja'?'もう一度、作品から':'Return to the finished work')+'</span></a>'}</nav></footer>
    ${i===23?`<section class="references"><h2>${t.references}</h2>${references.map(r=>`<p><a href="${r.url}" target="_blank" rel="noopener">${r.name} ↗</a><br><span>${esc(r.note[lang])}</span></p>`).join('')}</section>`:''}
  </article>`).join('');
  const html=`<!doctype html><html lang="${lang}" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="theme-color" content="#f5f2eb"><title>LISP ATELIER — ${lang==='ja'?'FPSから学ぶCommon Lispの教科書':'Common Lisp, learned through an arena FPS'}</title><meta name="description" content="${lang==='ja'?'Lisp未経験から壁キックとbotを備えたFPSを再構築する、24章の実践教科書。日本語・英語、実験室、演習、完成ソースを収録。':'An illustrated, bilingual 24-chapter Common Lisp course. Learn from first expressions to building and modifying an arena FPS with wall kicks and bots.'}"><link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}assets/style.css"><script>try{const t=localStorage.getItem('atelier-theme');if(t)document.documentElement.dataset.theme=t}catch{}</script><script type="module" src="${base}assets/app.js"></script></head><body><a class="skip-link" href="#reader">${lang==='ja'?'本文へ移動':'Skip to the text'}</a><header class="masthead"><button id="toc-toggle" class="icon-button" aria-controls="contents" aria-expanded="false" aria-label="${t.toc}">☰</button><a href="#orientation" class="wordmark">LISP <em>ATELIER</em><span>A FIELD GUIDE TO COMMON LISP</span></a><span class="edition">THE ARENA EDITION / 01</span><nav class="tools" aria-label="${lang==='ja'?'読書ツール':'Reading tools'}"><a id="language-link" href="${lang==='ja'?'./en/':'../'}" lang="${lang==='ja'?'en':'ja'}" aria-label="${lang==='ja'?'Read in English':'日本語で読む'}">${lang==='ja'?'JA <span>/ EN</span>':'<span>JA /</span> EN'}</a><button data-dialog="glossary" class="desktop-tool">${t.glossary}</button><button data-dialog="source-index" class="desktop-tool">${t.sources}</button><button id="theme-toggle" aria-label="${lang==='ja'?'配色を切り替える':'Toggle color theme'}">◐</button></nav></header>
    <aside id="contents" class="contents"><div class="contents-top"><p class="eyebrow">${t.toc} <span>00—23</span></p><label class="search-box"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="${t.search}" aria-label="${t.search}" autocomplete="off"></label><div id="search-status" role="status" class="small-note"></div></div><nav class="toc-links" aria-label="${t.toc}">${links}<div id="glossary-search"></div></nav><div class="contents-bottom"><div class="progress-label"><span>${t.progress}</span><strong id="progress-label">0 / 24</strong></div><progress id="progress" max="24" value="0" aria-label="${t.progress}"></progress><div class="book-links"><a href="${base}assets/atelier-course.zip" download>${t.download} ↓</a><a href="${repo}" target="_blank" rel="noopener">GITHUB ↗</a></div></div></aside>
    <div class="reader-shell"><div class="reading-bar"><span id="current-section">00 / PRELUDE</span><div><button data-dialog="glossary" class="mobile-tool">${t.glossary}</button><button data-dialog="source-index" class="mobile-tool">${t.sources}</button><button id="font-toggle" aria-label="${lang==='ja'?'本文サイズを切り替える':'Toggle text size'}">Aa</button><button id="print-button" aria-label="${lang==='ja'?'現在の章を印刷':'Print this chapter'}">${lang==='ja'?'印刷':'Print'}</button></div></div><main id="reader" tabindex="-1">${articles}</main><footer class="colophon"><span>LISP ATELIER</span><p>${lang==='ja'?'学びは、変えられる力になる。':'Understanding becomes the power to change.'}</p><small>© 2026 dikmri · MIT · JA / EN</small></footer></div>
    <dialog id="glossary"><div class="dialog-head"><div><p class="eyebrow">A WORKING VOCABULARY</p><h2>${t.glossary}</h2></div><button class="dialog-close" aria-label="${t.close}">×</button></div><input class="glossary-filter" type="search" placeholder="${lang==='ja'?'用語を絞り込む':'Filter terms'}" aria-label="${lang==='ja'?'用語を絞り込む':'Filter terms'}">${glossary.map(([word,note,id])=>`<div class="glossary-item" data-term="${esc(word+' '+note[lang])}"><a href="#${id}">${word} ↗</a><p>${esc(note[lang])}</p></div>`).join('')}</dialog>
    <dialog id="source-index"><div class="dialog-head"><div><p class="eyebrow">THE COMPLETE IMPLEMENTATION</p><h2>${t.sources}</h2></div><button class="dialog-close" aria-label="${t.close}">×</button></div><p>${lang==='ja'?'実行できる完成ソースです。まず関数名を探し、呼び先と状態変更をたどってください。':'The runnable, complete source. Find a function, then trace its calls and state changes.'}</p><label class="file-picker">${lang==='ja'?'ファイル':'File'} <select id="source-file">${files.map(f=>`<option>${f}</option>`).join('')}</select></label><a id="source-github" href="${repo}/blob/main/game/platform.lisp" target="_blank" rel="noopener">GitHub ↗</a><div id="source-code"></div></dialog>
    <script type="application/json" id="book-data">${JSON.stringify({lang,glossary:glossary.map(([word,note,id])=>({word,note:note[lang],id})),sources:raw}).replace(/</g,'\\u003c')}</script>
  </body></html>`;
  await writeFile(new URL('../public/'+(lang==='ja'?'index.html':'en/index.html'),import.meta.url),html.replace(/^[ \t]+$/gm,''));
}
for(const name of ['style.css','favicon.svg'])await copyFile(new URL('../src/'+name,import.meta.url),new URL('../public/assets/'+name,import.meta.url));
for(const name of ['app','labs'])await writeFile(new URL('../public/assets/'+name+'.js',import.meta.url),stripTypeScriptTypes(await readFile(new URL('../src/'+name+'.ts',import.meta.url),'utf8')).replace(/^[ \t]+$/gm,''));
await mkdir(new URL('../public/workshop/',import.meta.url),{recursive:true});
for(const [i,c] of chapters.entries()){
  const loads=c.model?`(load (merge-pathnames "../game/platform.lisp" *load-truename*))\n${i===9?'':'(load (merge-pathnames "../game/arena.lisp" *load-truename*))\n'}${i===23?'(load (merge-pathnames "../game/checks.lisp" *load-truename*))\n':''}(in-package :slipstream)\n`:'';
  const demo=i===9?`\n(unless (member "--check" sb-ext:*posix-argv* :test #'string=)\n  (load (merge-pathnames "window-demo.lisp" *load-truename*)))\n`:'';
  const body=`; LISP ATELIER / ${num(i)} ${c.id}\n; Run from repository root: sbcl --script workshop/${num(i)}-${c.id}.lisp\n; Change one value, predict, run, compare.\n${loads}\n${c.test}\n(format t "PASS / ${num(i)} ${c.id}~%")\n${demo}`;
  await writeFile(new URL('../workshop/'+num(i)+'-'+c.id+'.lisp',import.meta.url),body);
}
for(const name of await readdir(new URL('../workshop/',import.meta.url)))await copyFile(new URL('../workshop/'+name,import.meta.url),new URL('../public/workshop/'+name,import.meta.url));
console.log(`Built ${chapters.length} chapters in Japanese and English.`);
await import('./zip.ts');
