export type Lang = 'ja' | 'en';
export type Bi = Record<Lang, string>;
export const b = (ja: string, en: string): Bi => ({ja, en});
export type Section = {title: Bi; paragraphs: Bi[]; code?: string; lab?: string};
export type Chapter = {
  id: string; part: number; minutes: number; title: Bi; subtitle: Bi;
  goals: Bi[]; sections: Section[]; sources: {file: string; names: string[]}[];
  exercise: {task: Bi; hint: Bi; solution: string; explanation: Bi};
  quiz: {question: Bi; options: Bi[]; correct: number; explanation: Bi};
  test: string; model?: boolean;
};
export const s = (title: Bi, paragraphs: Bi[], code?: string, lab?: string): Section => ({title, paragraphs, code, lab});
export const ex = (task: Bi, hint: Bi, solution: string, explanation: Bi) => ({task,hint,solution,explanation});
export const q = (question: Bi, options: Bi[], correct: number, explanation: Bi) => ({question,options,correct,explanation});
export const source = (file: string, ...names: string[]) => ({file,names});

export const parts = [
  b('序曲 — 作品から始める', 'Prelude — Begin with the finished work'),
  b('Ⅰ — Lispという思考の道具', 'I — Lisp as a way of thinking'),
  b('Ⅱ — 世界に形と時間を与える', 'II — Give the world shape and time'),
  b('Ⅲ — アリーナを生きた場所にする', 'III — Bring the arena to life'),
  b('Ⅳ — 作る人から、変えられる人へ', 'IV — From builder to independent creator')
];

export const chapters: Chapter[] = [
{
id:'orientation',part:0,minutes:25,title:b('完成形から、最初の一行へ','From a finished arena to your first line'),
subtitle:b('読む、予測する、実行する、変える。その循環を、この一冊の学び方にする。','Read, predict, run, change. Make that cycle your method for learning.'),
goals:[b('何を自分で作れるようになるかを把握する','Understand exactly what you will be able to build'),b('Common Lisp・SBCL・raylibの役割を区別する','Separate the roles of Common Lisp, SBCL, and raylib'),b('演習と完成ソースの使い分けを覚える','Know when to use a workshop and when to inspect the finished source')],
sections:[
s(b('この本の到達点','The work you are learning to make'),[
b('SLIPSTREAMは、立体アリーナを走り、壁を蹴り、botと戦うWindows用のFPSです。この教材はその実装を題材にします。最終目標は完成コードを暗記することではありません。入力が速度になり、速度が位置になり、命中が得点になる流れを説明し、仕様を変え、壊れていないことを確かめられる状態です。','SLIPSTREAM is a Windows arena FPS with three-dimensional movement, wall kicks, and bot opponents. Its implementation is the subject of this book. The goal is not to memorize its code. You should be able to explain how input becomes velocity, velocity becomes position, and a hit becomes a score; then change that behavior and verify the result.'),
b('学習用の実装は独自の小規模アリーナFPSです。Quake IIIのエンジン、マップ、モデルを移植したものではなく、ネットワーク対戦や本格的なアニメーションモデルも含みません。この境界を知ると、「今のコードで改善できること」と「別の設計が必要なこと」を区別できます。','The teaching project is an original, small arena FPS. It does not port Quake III’s engine, maps, or models, and it does not include network multiplayer or a full character animation system. Knowing that boundary helps you distinguish an improvement to this implementation from a feature that needs a new design.')]),
s(b('三つの層を混同しない','Three layers, three responsibilities'),[
b('Common Lispは言語、SBCLはそのプログラムを実行・コンパイルする処理系です。raylibはウィンドウ、GPU描画、入力、音声を扱うライブラリ。ゲームのルール、物理、衝突、射撃、bot、試合進行はLispにあり、native/bridge.cはraylibを単純な引数で呼ぶ境界です。「LispだけでGPUまで実装する」ことが到達点ではありません。','Common Lisp is the language. SBCL runs and compiles programs written in it. raylib handles the window, GPU drawing, input, and audio. The game’s rules, physics, collision, weapons, bots, and match progression live in Lisp; native/bridge.c exposes raylib through simple arguments. Implementing a GPU library in Lisp is not the goal.'),
b('この本は前提知識を順に導入します。第1〜7章でLispの表記とデータを覚え、第8〜12章で時間・描画・移動を作り、第13〜18章で戦闘とbotを完成させます。最後の5章ではマクロ、検証、性能、改造を扱います。数学は必要になった場面で図と数値から説明します。','The book introduces prerequisites in order. Chapters 1–7 teach Lisp notation and data. Chapters 8–12 build time, rendering, and movement. Chapters 13–18 complete combat and bots. The final five chapters cover macros, verification, performance, and modifications. Mathematics is introduced through diagrams and numbers when you need it.')]),
s(b('一章を学ぶ四つの動作','A repeatable learning loop'),[
b('まず例を読み、実行する前に結果を予測します。次にworkshop/の章別スクリプトをSBCLで実行し、予測と比較します。三つ目に演習を自分で書き、解答を開く前に少なくとも一度動かします。最後に「実装の現場」を開き、同じ概念が実ゲームでどこに使われているかをたどります。','First read an example and predict its result before running it. Execute the chapter’s workshop script in SBCL and compare. Write your own exercise solution and run it at least once before revealing the answer. Finally open “Inside the implementation” to see where the same concept appears in the real game.'),
b('最初にリポジトリを取得してください。ゲームはgame/、演習はworkshop/、教科書はpublic/にあります。各章の実行コマンドはリポジトリの最上位から使います。学習済みの印はこのブラウザだけに保存され、アカウントやサーバーへの送信はありません。読了時間は目安です。手を動かす時間は人によって大きく変わります。','Download or clone the repository first. The game is in game/, workshops in workshop/, and the textbook in public/. Run each chapter’s command from the repository root. Completion marks are stored only in this browser; no account or server submission is involved. Reading times are estimates. The time needed for practice varies considerably.')],
'git clone https://github.com/dikmri/slipstream-lisp-textbook.git\ncd slipstream-lisp-textbook\nsbcl --script workshop/00-orientation.lisp')],
sources:[source('main.lisp','main'),source('arena.lisp','start-match')],
exercise:ex(b('紙に「入力 → 移動 → 衝突 → 射撃 → 描画」の流れを書き、各段階に対応するファイルを一つずつ付けてください。','Write an input → movement → collision → shooting → rendering chain and assign a source file to each stage.'),b('main.lisp、arena.lisp、view.lisp、platform.lispを役割で分けます。','Separate main.lisp, arena.lisp, view.lisp, and platform.lisp by responsibility.'),'; Input: main.lisp / platform.lisp\n; Movement, collision, shooting: arena.lisp\n; Presentation: view.lisp\n; OS / GPU / audio boundary: native/bridge.c',b('重要なのはファイル数ではなく、変更がどの層に波及するかです。射撃ダメージを変えるだけならGPU側の変更は不要です。','What matters is the boundary a change crosses. Changing shot damage does not require changing the GPU layer.')),
quiz:q(b('この教材のゲームルールを主に実行するものは？','What primarily executes this game’s rules?'),[b('raylibのモデル描画','raylib model drawing'),b('SBCLで動くCommon Lisp','Common Lisp running in SBCL'),b('教科書のJavaScript','The textbook’s JavaScript')],1,b('教科書の実験室は図解です。実ゲームの処理系はSBCLであり、ブラウザがFPSのLispを実行しているわけではありません。','The labs are illustrations. SBCL runs the game; the browser is not executing the FPS’s Lisp code.')),
test:'(assert (= (+ 1 2) 3))\n(format t "Workshop ready.~%")'
},
{
id:'setup',part:1,minutes:40,title:b('机を整える — SBCLとREPL','Prepare your desk — SBCL and the REPL'),
subtitle:b('環境の問題と、プログラムの問題を分けられるようになる。','Learn to distinguish an environment problem from a program problem.'),
goals:[b('SBCLを起動し、式を評価する','Start SBCL and evaluate an expression'),b('REPLとスクリプト実行を使い分ける','Distinguish interactive and script execution'),b('FPSに必要な追加ツールを確認する','Check the extra tools required by the FPS')],
sections:[
s(b('Windowsで最初の式を動かす','Run your first expression on Windows'),[
b('PowerShellでwinget install --id SBCL.SBCL --exactを実行します。導入後は新しいPowerShellを開き、sbcl --versionで確認してください。PATHは既に開いている端末へ自動では反映されません。見つからない場合は、標準導入先の実行ファイルをフルパスで呼ぶと、導入失敗とPATH未更新を区別できます。','In PowerShell run winget install --id SBCL.SBCL --exact. Open a new PowerShell afterward and verify with sbcl --version. A PATH update does not automatically reach a terminal that was already open. Calling the executable by its full installation path distinguishes a failed installation from a stale PATH.'),
b('sbclを起動するとREPLが現れます。Readで式を読み、Evalで評価し、Printで結果を表示し、Loopで次の入力へ戻ります。下の(+ 2 3)だけを入力し、5が返ることを確認します。終了は(sb-ext:exit)です。sb-ext:はSBCL固有の名前空間なので、ここはCommon Lisp標準そのものではありません。','Running sbcl opens its REPL: Read an expression, Eval it, Print the result, Loop for the next input. Enter just (+ 2 3) and verify that it returns 5. Exit with (sb-ext:exit). The sb-ext: prefix denotes SBCL’s extension namespace; that exit call is not part of the Common Lisp standard.')],
'# PowerShell\nwinget install --id SBCL.SBCL --exact\nsbcl --version\nsbcl\n\n; Inside SBCL, not in PowerShell:\n(+ 2 3)\n(sb-ext:exit)'),
s(b('ファイルとして実行する','Move from the prompt to a file'),[
b('REPLは小さな実験に適し、.lispファイルは再現可能なプログラムに適します。例えば(format t "Hello, arena!~%")をhello.lispとして保存し、PowerShellからsbcl --script hello.lispを実行します。formatのtは標準出力、~%は改行です。REPLの「*」プロンプトや表示された結果はファイルへコピーしません。','The REPL is ideal for small experiments; a .lisp file makes a program reproducible. Save (format t "Hello, arena!~%") as hello.lisp and run sbcl --script hello.lisp from PowerShell. In format, t selects standard output and ~% inserts a newline. Do not copy the REPL’s * prompt or its printed results into the file.'),
b('失敗すると条件名とバックトレースが出ます。まず最初のエラー行と、そこに表示されたファイル名・行番号を読みます。「関数が未定義」と「ファイルがない」は別の問題です。初心者の段階では、何度も式を打ち直すよりファイルを直し、新しいプロセスで再実行すると状態の混乱を防げます。','A failure produces a condition name and backtrace. Start with the first error and its file or line information. An undefined function and a missing file are different problems. Early in your learning, editing the file and rerunning it in a fresh process avoids confusion caused by previous interactive definitions.')],
'; hello.lisp\n(format t "Hello, arena!~%")\n\n; Repository workshop, from PowerShell:\n; sbcl --script workshop/01-setup.lisp'),
s(b('FPSのビルドに必要なもの','What the native FPS build needs'),[
b('章別の計算演習はSBCLだけで動きます。完成FPSをビルドするには、Windows x64、SBCL、64ビットMinGW GCC、OpenGL対応GPUが必要です。MSYS2のMinGW x64環境ならpacman -S mingw-w64-x86_64-gccでコンパイラを導入し、そのbinをPATHへ追加します。この操作はMSYS2の端末で行い、ゲームのbuild.ps1はPowerShellで実行します。','The numerical workshops require only SBCL. Building the complete FPS requires Windows x64, SBCL, 64-bit MinGW GCC, and an OpenGL-capable GPU. In an MSYS2 MinGW x64 environment, install the compiler with pacman -S mingw-w64-x86_64-gcc and add its bin directory to PATH. Run that installation command in the MSYS2 terminal; run the game’s build.ps1 in PowerShell.'),
b('game/build.ps1は固定バージョンのraylib 5.5を必要に応じて公式配布から取得し、Cの境界をarena.dllにし、LispをSlipstream.exeに保存します。初回のraylib取得にはネット接続が必要です。この教材のネイティブビルドはWindows向けです。Linux/macOSでも言語演習は学べますが、ゲームには共有ライブラリ名とCビルド手順の移植が必要です。','game/build.ps1 downloads the pinned raylib 5.5 distribution when needed, builds the C boundary as arena.dll, and saves Lisp as Slipstream.exe. The initial raylib download requires an internet connection. This native build targets Windows. The language workshops also teach concepts usable on Linux and macOS, but porting the game requires changing the shared-library name and C build procedure.')],
'# PowerShell, from the repository root\ngcc --version\nsbcl --version\ncd game\n.\\build.ps1\n.\\play.cmd')],
sources:[source('build.lisp'),source('build.ps1')],
exercise:ex(b('REPLとスクリプトの両方で42を表示してください。シェルへ打つコマンドと、Lispの式を区別して記録します。','Display 42 in both the REPL and a script. Record which line is a shell command and which is a Lisp expression.'),b('REPLでは式の結果も表示されます。スクリプトではformatを使います。','The REPL prints expression results. A script needs an explicit format call.'),'(+ 40 2)\n(format t "~D~%" (+ 40 2))',b('~Dは整数を十進表示します。スクリプトで(+ 40 2)だけを書いても、結果の自動表示はありません。','~D prints an integer in decimal. A bare (+ 40 2) in a script does not automatically print its result.')),
quiz:q(b('インストール直後、古い端末でsbclが見つからない。最初に試すことは？','An old terminal cannot find sbcl just after installation. What should you try first?'),[b('Lispの括弧を変更する','Change the Lisp parentheses'),b('新しい端末でsbcl --versionを試す','Open a new terminal and run sbcl --version'),b('毎回raylibを再インストールする','Reinstall raylib every time')],1,b('環境変数の更新とコードの構文は別です。処理系が起動するまで構文を直しても解決しません。','An environment update and a syntax change are separate. Fixing syntax cannot help if the runtime has not started.')),
test:'(assert (= (+ 40 2) 42))\n(format t "~D~%" (+ 40 2))'
},
{
id:'expressions',part:1,minutes:45,title:b('括弧は、思考の輪郭','Parentheses are the outline of thought'),
subtitle:b('式を左から眺めるのではなく、内側から読めるようになる。','Read an expression from the inside out, not merely from left to right.'),
goals:[b('前置記法と入れ子を読める','Read prefix notation and nesting'),b('数・文字列・シンボル・リストを区別する','Distinguish numbers, strings, symbols, and lists'),b('quoteが評価を止める理由を説明する','Explain why quote prevents evaluation')],
sections:[
s(b('一つの形で書く','One shape for function calls'),[
b('関数呼び出しは(関数名 引数…)です。(+ 2 3)なら+を2と3へ適用します。(* (+ 2 3) 4)は内側の足し算を評価して5を得て、それを4倍します。括弧は装飾ではなく、どこまでが一つの式かを示す構造です。改行やインデントは読みやすさのためであり、演算の優先順位を変えません。','A function call has the shape (function argument…). (+ 2 3) applies + to 2 and 3. (* (+ 2 3) 4) evaluates the inner addition to 5, then multiplies by 4. Parentheses are structure, not decoration: they mark the extent of an expression. Indentation and line breaks improve readability but do not change precedence.'),
b('ゲームの位置更新も同じ形です。(+ position (* velocity dt))は「現在位置＋速度×経過秒」。速度12 m/s、dtが1/120秒なら、1回で0.1 m進みます。数字を変えて式を読むだけで、移動処理の核へもう触れています。セミコロンから行末はコメントなので実行されません。','Position updates use the same shape: (+ position (* velocity dt)) means current position plus velocity times elapsed seconds. At 12 m/s and dt = 1/120 second, one update moves 0.1 m. You are already reading the core of movement. A semicolon begins a comment that continues to the end of the line.')],
'(+ 2 3)                 ; => 5\n(* (+ 2 3) 4)           ; => 20\n(+ 10 (* 12 (/ 1 120)))  ; => 101/10', 'reader'),
s(b('Lispが扱う値','The values Lisp works with'),[
b('整数12、浮動小数12.0、正確な有理数1/120は異なる数の表現です。Common Lispの(/ 1 120)は近似小数ではなく比を返します。単精度の型を意識する境界では1.0f0を使います。文字列は"VEX"、シンボルはhpのような名前です。キーワード:healthは自身を評価した値で、アイテムの種類を表すラベルとして便利です。','The integer 12, floating-point number 12.0, and exact rational 1/120 represent numbers differently. Common Lisp’s (/ 1 120) returns an exact ratio rather than an approximate decimal. Use 1.0f0 where single precision matters. A string is written "VEX"; a symbol is a name such as hp. The keyword :health evaluates to itself and is useful as an item-kind label.'),
b('NILは空のリストでも偽でもあり、Tは代表的な真の値です。実際にはNIL以外の値はすべて条件で真として扱われ、0も空文字列も真です。JavaScriptやPythonの「ゼロは偽」という感覚を持ち込まないでください。射線距離が0のときも、命中が存在することを表せます。','NIL is both the empty list and false. T is the conventional true value, but every non-NIL value is true in a condition, including 0 and an empty string. Do not import JavaScript or Python’s falsy-zero intuition. A ray hit at distance 0 can still represent a real hit.')],
'(/ 1 120)     ; => 1/120\n(/ 1.0f0 120) ; => a single-float approximation\n(if 0 :yes :no) ; => :YES\n(list "VEX" :health nil) ; => ("VEX" :HEALTH NIL)'),
s(b('コードを、データとして置く','Put code-shaped data on the table'),[
b('(+ 2 3)は関数呼び出しですが、\'(+ 2 3)は三つの要素からなるリストです。先頭の\'は(quote …)の省略。quoteは引数を通常のように評価しません。(first \'(+ 2 3))はシンボル+を返します。これがマクロへつながる基礎ですが、今は「地図のアイテム配置表は実行したい式ではない」ことを理解すれば十分です。','(+ 2 3) is a call, while \'(+ 2 3) is a three-element list. The apostrophe abbreviates (quote …), which prevents normal evaluation of its argument. (first \'(+ 2 3)) returns the symbol +. This is a foundation for macros; for now, understand that a map’s item-placement table is data rather than a list of calls to execute.'),
b('よくあるエラーは閉じ括弧不足と、データへquoteを付け忘れることです。エディタの対応括弧表示を使い、外側を一つ書いてから内部を埋めます。下の構造実験室は括弧を可視化する教材であり、Common Lispの処理系ではありません。式の実行結果はSBCLで確かめます。','Common early errors are missing a closing parenthesis and forgetting to quote data. Use your editor’s matching-parenthesis feature, write the outer pair, then fill in its contents. The structure lab visualizes nesting; it is not a Common Lisp runtime. Verify expression results in SBCL.')],
"(first '(+ 2 3))\n(second '(0 1.2 0 :mega))\n(quote (:health :armor :rail))")],
sources:[source('arena.lisp','make-arena')],
exercise:ex(b('速度18、dtが1/120、現在位置7の次の位置を一つの式で書いてください。次にその式を評価せずリストとして返します。','Write one expression for the next position at speed 18, dt = 1/120, and position 7. Then return that expression as unevaluated data.'),b('quoteは最も外側の式へ付けます。','Quote the outermost expression.'),"(+ 7 (* 18 (/ 1 120)))\n'(+ 7 (* 18 (/ 1 120)))",b('結果は143/20、つまり7.15です。二つ目は数値ではなく、同じ計算を表すリストになります。','The result is 143/20, or 7.15. The second expression returns the list describing that calculation rather than a number.')),
quiz:q(b('(if 0 :hit :miss)の結果は？','What is the result of (if 0 :hit :miss)?'),[b(':MISS',':MISS'),b('エラー','An error'),b(':HIT',':HIT')],2,b('0はNILではないので真です。数値判定にはzerop、plusp、比較関数を明示的に使います。','0 is not NIL, so it is true. Use zerop, plusp, or comparisons for numeric conditions.')),
test:"(assert (= (* (+ 2 3) 4) 20))\n(assert (= (+ 7 (* 18 (/ 1 120))) 143/20))\n(assert (eq (if 0 :hit :miss) :hit))\n(assert (eq (first '(+ 2 3)) '+))"
},
{
id:'bindings',part:1,minutes:50,title:b('値に名前と寿命を与える','Give a value a name and a lifetime'),
subtitle:b('letとsetfが読めれば、ゲームの状態を追える。','With let and setf, you can follow the state of a game.'),
goals:[b('letとlet*の評価順を区別する','Distinguish the initialization order of let and let*'),b('局所変数と特別変数の役割を理解する','Understand lexical locals and special variables'),b('setfで値を変更し、変更箇所を追跡する','Change values with setf and trace the writes')],
sections:[
s(b('letは、小さな作業机','let creates a local workbench'),[
b('(let ((speed 12) (dt 1/120)) (* speed dt))では、speedとdtをそのletの内部だけで使えます。この範囲をスコープと呼びます。letの初期値は外側の環境で評価され、同じletで定義した兄弟変数は参照できません。前の変数を使って次を計算したい場合はlet*を使います。','In (let ((speed 12) (dt 1/120)) (* speed dt)), speed and dt are available only inside that let. This extent is their scope. A let’s initial values are evaluated in the surrounding environment, not in an environment containing their sibling bindings. Use let* when the next initialization depends on a previous one.'),
b('move-bodyはpを位置、velocityを速度、old-yを更新前の高さへ結び付けます。長い式に名前を付けるのは文字を節約するためではなく、何を意味する値かを示すためです。初期値を依存順に計算するraycastではlet*が多く、独立した値を扱う場所ではletで十分です。','move-body binds p to position, velocity to velocity, and old-y to the previous height. Naming an expression is not just a way to save typing; it documents what the value means. Raycasting often uses let* because later values depend on earlier ones. let is enough for independent bindings.')],
'(let ((speed 12) (dt 1/120))\n  (* speed dt))\n\n(let* ((speed 12)\n       (dt 1/120)\n       (step (* speed dt)))\n  (+ 10 step))'),
s(b('状態を変えるときの文法','The syntax of changing state'),[
b('setfは「場所」に値を書き込みます。(setf hp 75)だけでなく、(setf (actor-hp player) 75)や(setf (aref ammo 2) 10)も同じ形式です。incfとdecfはその場所を増減します。更新する前に旧値を保存する必要があるか考えます。衝突では更新前の高さと候補の高さを比較するため、順序が動作を決めます。','setf stores a value in a place. The same form handles (setf hp 75), (setf (actor-hp player) 75), and (setf (aref ammo 2) 10). incf and decf increase or decrease a place. Decide whether you need the old value before writing. Collision compares old and proposed heights, so the order of updates determines behavior.'),
b('setfに複数の場所と値を並べると、左から順に変更されます。構造体を指す二つの変数が同じオブジェクトを共有していると、片方での変更がもう片方にも見えます。変数の名前を付けることと、オブジェクトを複製することは別です。この違いはベクトルとactorで再び確認します。','Multiple place/value pairs in setf are processed left to right. If two variables refer to the same structure, a write through either reference is visible through the other. Naming an object and copying it are different operations. You will meet that distinction again with vectors and actors.')],
'(let ((hp 100) (armor 25))\n  (decf hp 10)\n  (incf armor 5)\n  (setf hp (min hp 100))\n  (list hp armor)) ; => (90 30)'),
s(b('星付きの名前と再読み込み','Starred names and reloading'),[
b('defparameterは初期値を毎回設定し、defvarは既に束縛されている値を通常は置き換えません。*player*や*state*の星は「特別変数」の慣例です。これらは動的スコープを持ち、letで一時的に束縛すると、その実行範囲で呼ばれる関数からもその値が見えます。自己テストが*native-ready*をNILにするのは、その仕組みを利用しています。','defparameter initializes on each evaluation; defvar normally preserves an existing binding. Stars in names such as *player* and *state* conventionally identify special variables. They have dynamic scope: a temporary let binding is visible to functions called within its execution. The self-test uses that mechanism to bind *native-ready* to NIL.'),
b('defconstantは定数を宣言します。調整中の速度や難易度を頻繁に再定義するならdefparameterの方が適しています。ソースをloadし直したのに設定が変わらないときは、まずdefvarかどうかを確認してください。特別変数は手軽ですが、大きなゲームを複数同時に動かす設計では明示的な状態オブジェクトが必要になります。','defconstant declares a constant. A tunable speed or difficulty that you repeatedly redefine is better suited to defparameter. If loading a file again does not change a setting, check whether it uses defvar. Special variables are convenient here, but running multiple independent matches in a larger application would require explicit state objects.')],
'(defparameter *training-speed* 12)\n(let ((*training-speed* 20))\n  (* *training-speed* 1/120))\n*training-speed* ; => 12')],
sources:[source('arena.lisp','move-body'),source('checks.lisp','self-test')],
exercise:ex(b('HP100からダメージ35を引き、0未満にならないようにする局所計算を書いてください。','Write a local calculation that subtracts 35 damage from 100 HP and never leaves HP below 0.'),b('maxで下限を設定し、setfで書き戻します。','Use max for the lower bound and setf to write the result.'),'(let ((hp 100) (damage 35))\n  (setf hp (max 0 (- hp damage)))\n  hp)',b('副作用はletの局所変数に限定されます。damageを200にすると0が返ることも確かめます。','The mutation is limited to the local binding. Also verify that changing damage to 200 returns 0.')),
quiz:q(b('同じ束縛リストの前の値を、次の初期値で使うには？','How can a binding initializer use a preceding binding in the same list?'),[b('let*を使う','Use let*'),b('quoteを付ける','Add quote'),b('変数名を大文字にする','Capitalize the variable name')],0,b('let*は初期値を順次評価し、既に作った束縛を後の式へ見せます。','let* evaluates initializers sequentially and makes earlier bindings available to later ones.')),
test:'(assert (= (let* ((speed 12) (dt 1/120) (step (* speed dt))) (+ 10 step)) 101/10))\n(assert (= (let ((hp 100) (damage 200)) (setf hp (max 0 (- hp damage))) hp) 0))'
},
{
id:'functions',part:1,minutes:55,title:b('関数は、意味を持つ道具','Functions are tools with a purpose'),
subtitle:b('入力、結果、副作用。三つを分けて読める関数を書く。','Write functions whose inputs, results, and effects you can explain.'),
goals:[b('defunと引数リストを使う','Use defun and lambda lists'),b('関数を値として渡す','Pass a function as a value'),b('複数値と局所関数を読む','Read multiple values and local functions')],
sections:[
s(b('関数に約束を与える','Give a function a contract'),[
b('(defun clamp (x lo hi) …)はclampという関数を定義します。呼び出すときは(clamp 175 0 100)。本体の最後の式が通常の戻り値になります。まず「受け取るもの」「返すもの」「変更するもの」を一文で説明してから書くと、長い処理でも境界が明確になります。clampは数を返すだけですが、hurtはactorを変更します。','(defun clamp (x lo hi) …) defines a function named clamp; call it with (clamp 175 0 100). The final body expression normally supplies the result. Before writing a function, describe what it receives, returns, and changes. clamp only returns a number; hurt mutates an actor.'),
b('&optionalは省略できる引数を表します。(defun boost (speed &optional (extra 4)) …)ならboostへ一つだけ引数を渡してもextraは4です。&keyは名前付き引数で、make-actor :hp 100のような読みやすい構築に使われます。デフォルト値は呼び出し時に評価されるので、可変ベクトルの初期値を毎回作れます。','&optional introduces optional arguments. In (defun boost (speed &optional (extra 4)) …), extra defaults to 4 when omitted. &key introduces named arguments, as in the readable construction make-actor :hp 100. Defaults are evaluated at call time, which lets a constructor create a fresh mutable vector for each instance.')],
'(defun bounded-hp (hp damage)\n  (max 0 (- hp damage)))\n\n(defun boost (speed &optional (extra 4))\n  (+ speed extra))\n\n(bounded-hp 100 35) ; => 65\n(boost 12)          ; => 16'),
s(b('関数を別の関数へ渡す','Pass behavior as a value'),[
b('Common Lispは変数と関数の名前空間を区別します。関数の値を取り出す記法は#\'で、(mapcar #\'abs \'(-3 2 -1))のように渡します。値として持った関数を呼ぶにはfuncallを使います。lambdaは名前を付けない関数です。botの候補へ点数を付ける場面では、小さなlambdaをその場で渡すと処理の目的が近くに置けます。','Common Lisp distinguishes variable and function namespaces. #\' retrieves a function value, as in (mapcar #\'abs \'(-3 2 -1)). Use funcall to call a function stored as a value. lambda creates an anonymous function. When scoring bot candidates, a small lambda can keep the scoring rule beside the traversal that uses it.'),
b('fletは局所関数を定義します。自分自身を再帰的に呼ぶ局所関数ならlabelsを使います。「一度しか使わないから全部lambdaにする」必要はありません。checkのように名前で目的を伝えたい局所処理はfletにすると読みやすくなります。','flet defines local functions; use labels when those local functions need to call themselves recursively. Not every one-off function needs to be anonymous. A local helper such as check is clearer with a name that communicates its purpose.')],
"(mapcar #'abs '(-3 2 -1)) ; => (3 2 1)\n(funcall (lambda (x) (* x x)) 5) ; => 25\n\n(flet ((alive-p (hp) (> hp 0)))\n  (alive-p 10))"),
s(b('一つの呼び出しで複数の結果','More than one result from a call'),[
b('valuesは複数値を返します。player-inputは移動方向、射撃の有無、ジャンプ保持の有無を別々に返し、mainはmultiple-value-bindで受け取ります。これはリストを返すことと同じではありません。普通に一つの値として受け取ると主値だけが使われます。','values returns multiple values. player-input returns movement direction, firing state, and jump-held state separately; main receives them with multiple-value-bind. Multiple values are not a list. An ordinary single-value context uses only the primary value.'),
b('早く関数を終えるときにはreturn-fromと関数名を使います。例えばray-boxは軸の区間が交わらないと分かった時点でNILを返します。関数を小さく分ける基準は行数ではなく、説明できる一つの仕事かどうかです。','Use return-from with the function’s name to return early. ray-box returns NIL as soon as an axis interval proves that no intersection is possible. A good function boundary is one explainable responsibility, not an arbitrary line count.')],
'(defun movement-input ()\n  (values 1 0 t))\n\n(multiple-value-bind (x z jump-p) (movement-input)\n  (list x z jump-p)) ; => (1 0 T)')],
sources:[source('arena.lisp','clamp','ray-box'),source('main.lisp','player-input')],
exercise:ex(b('HPの上限を省略可能な引数にしたheal関数を書きます。通常の上限は100、メガヘルスでは175です。','Write heal with an optional HP limit. The normal limit is 100; mega health can pass 175.'),b('現在HP＋回復量をminで上限へ制限します。','Clamp current HP plus the heal amount with min.'),'(defun heal (hp amount &optional (limit 100))\n  (min limit (+ hp amount)))\n(assert (= (heal 90 35) 100))\n(assert (= (heal 90 75 175) 165))',b('メガヘルスの処理を通常の関数へ押し込まず、上限という仕様を引数で表現しています。','The limit is an explicit rule in the function’s inputs instead of an implicit special case.')),
quiz:q(b('変数fnに入れた関数を引数12で呼ぶ記法は？','How do you call the function in variable fn with argument 12?'),[b('(fn 12)','(fn 12)'),b('(funcall fn 12)','(funcall fn 12)'),b('(quote fn 12)','(quote fn 12)')],1,b('(fn 12)はfnという名前の関数を探します。変数の値に入った関数はfuncallで呼びます。','(fn 12) looks for a function named fn. funcall invokes the function value stored in the variable.')),
test:"(defun heal (hp amount &optional (limit 100)) (min limit (+ hp amount)))\n(assert (= (heal 90 35) 100))\n(assert (equal (mapcar #'abs '(-3 2 -1)) '(3 2 1)))\n(assert (equal (multiple-value-bind (x z j) (values 1 0 t) (list x z j)) '(1 0 t)))"
},
{
id:'collections',part:1,minutes:60,title:b('リスト、配列、ハッシュ表','Lists, arrays, and hash tables'),
subtitle:b('世界の集合を、目的に合う形で持つ。','Choose a representation that fits the work a collection must do.'),
goals:[b('リストとベクトルの違いを理解する','Understand the difference between lists and vectors'),b('mapcar・reduce・remove-ifを使う','Use mapcar, reduce, and remove-if'),b('ハッシュ表で座標を索引にする','Use coordinates as hash-table keys')],
sections:[
s(b('リストはつながり、ベクトルは添字','Links for lists, indexes for vectors'),[
b('リストはconsセルの連鎖です。firstとrestで先頭と残りを取り出し、pushで先頭へ追加し、popで先頭を外します。pushは変数が指すリストの先頭を変更します。アイテムや短命なエフェクトは追加・除去が多いため、このゲームではリストとして保持します。consは二つの値を組にするので、(cons ix iz)の結果は通常の二要素リストではなく、末尾が数のドット対です。','A list is a chain of cons cells. first and rest access its head and tail; push adds to the head and pop removes it. push changes the list held in its place. Items and short-lived effects are frequently added and removed, so this game stores them in lists. cons pairs two values: (cons ix iz) creates a dotted pair with a numeric tail, not an ordinary two-element list.'),
b('ベクトルは一次元配列で、(aref ammo 2)のように添字でアクセスします。#(180 24 16 16)はベクトルのリテラルですが、変更する実データは(vector 180 24 16 16)で新しく作ります。ソース中の定数リテラルを破壊的に変えると、コンパイルや共有に関わる未定義の問題を招きます。弾数の順序は武器番号と一致させます。','A vector is a one-dimensional array accessed by index, as in (aref ammo 2). #(180 24 16 16) is a vector literal; create mutable instance data with (vector 180 24 16 16). Destructively changing a constant literal can cause undefined behavior involving compilation or shared objects. Ammo order must match weapon indexes.')],
"(let ((items nil))\n  (push :health items)\n  (push :rail items)\n  (pop items)) ; => :RAIL\n\n(let ((ammo (vector 180 24 16 16)))\n  (decf (aref ammo 2))\n  (aref ammo 2)) ; => 15"),
s(b('集合へ意図を伝える','Express an operation on a collection'),[
b('mapcarは各要素へ関数を適用して新しいリストを作り、reduceは集合を一つの値へ畳み込みます。全botの撃破数を足すなら(reduce #\'+ actors :key #\'actor-kills)。remove-ifは条件に合う要素を除いたリストを返します。delete-ifは破壊的な操作を許される関数なので、共有されているリストへ安易に使わないでください。','mapcar applies a function to each element and creates a new list; reduce combines a collection into one value. Sum bot kills with (reduce #\'+ actors :key #\'actor-kills). remove-if returns a list without matching elements. delete-if is permitted to modify its input destructively, so use it carefully when a list may be shared.'),
b('sortやnreverseも破壊的操作を許されます。rankedが(copy-list *actors*)をsortするのは、描画のための順位変更でゲーム本体のactor順を変えないためです。破壊的な関数の戻り値は必ず受け取ります。先頭セルが変わることがあるからです。','sort and nreverse are also permitted to modify their inputs. ranked sorts (copy-list *actors*) so presentation order does not reorder the game’s actor list. Always retain the returned value of a destructive operation: the head of the result may be a different cell.')],
"(mapcar (lambda (x) (* x 2)) '(1 2 3))\n(reduce #'+ '(10 20 30))\n(remove-if #'minusp '(-1 0 3 -2))\n(sort (copy-list '(3 1 2)) #'<)"),
s(b('地図に住所を付ける','Give the map an address system'),[
b('build-navは座標(ix . iz)からノード番号を引くハッシュ表を使います。ここでは同じ値のconsを新しく作って検索するため:test #\'equalが必要です。eqでは同じオブジェクトそのものかどうかを比較するため、新しいconsで同じ座標を表しても一致しません。gethashは値と「登録されているか」の二つの値を返します。','build-nav uses a hash table from coordinates (ix . iz) to node indexes. It creates fresh cons keys during lookups, so it needs :test #\'equal. eq compares object identity and would not match a newly constructed pair for the same coordinates. gethash returns both the value and whether the entry is present.'),
b('ノード番号0も有効です。Common Lispでは0は真なのでwhen otherは0を除外しません。値にNILを登録する可能性がある表では、gethashの第二値を使って存在を判定します。配列・リスト・ハッシュ表を「速い順」で選ぶのではなく、添字、順序、キー検索のどれが必要かで選びます。','Node index 0 is valid. In Common Lisp, 0 is true, so when other does not exclude it. If NIL can itself be a stored value, use the second value from gethash to test presence. Choose an array, list, or hash table according to whether you need indexing, sequence traversal, or key lookup, rather than ranking them by a vague idea of speed.')],
"(let ((grid (make-hash-table :test #'equal)))\n  (setf (gethash (cons 1 2) grid) 0)\n  (multiple-value-bind (index present-p)\n      (gethash (cons 1 2) grid)\n    (list index present-p))) ; => (0 T)")],
sources:[source('arena.lisp','build-nav','update-rockets'),source('view.lisp','ranked')],
exercise:ex(b('弾数ベクトルから最大弾数を求め、正の弾数の武器番号だけをリストとして返してください。','Find the largest ammo count, then return only the indexes of weapons with positive ammo.'),b('loop for i below (length ammo)を使い、arefで判定できます。','Use loop for i below (length ammo) and inspect each entry with aref.'),'(let ((ammo (vector 0 12 0 8)))\n  (values (reduce #\'max ammo)\n          (loop for i below (length ammo)\n                when (plusp (aref ammo i)) collect i)))',b('結果は主値12、第二値(1 3)です。コレクションの種類を変換する必要はありません。','The primary result is 12 and the second is (1 3). There is no need to convert the vector first.')),
quiz:q(b('毎回新しく作る座標のconsをキーにするなら、比較は？','Which comparison fits freshly constructed cons keys containing coordinates?'),[b('eq','eq'),b('equal','equal'),b('常に=','Always =')],1,b('equalはconsの内容を再帰的に比較します。=は数値比較であり、consの比較には使えません。','equal recursively compares cons contents. = compares numbers and is not a cons-key comparison.')),
test:"(let ((ammo (vector 0 12 0 8))) (assert (= (reduce #'max ammo) 12)) (assert (equal (loop for i below (length ammo) when (plusp (aref ammo i)) collect i) '(1 3))))\n(let ((grid (make-hash-table :test #'equal))) (setf (gethash (cons 1 2) grid) 0) (assert (= (gethash (cons 1 2) grid) 0)))"
},
{
id:'control-flow',part:1,minutes:50,title:b('条件と反復で、ルールを書く','Write rules with conditions and iteration'),
subtitle:b('「いつ」「どれに」「何回」を、読める形で表す。','Express when, which, and how many in a form you can read.'),
goals:[b('if・when・cond・caseを適切に選ぶ','Choose among if, when, cond, and case'),b('dolist・dotimes・loopを読む','Read dolist, dotimes, and loop'),b('早期終了と短絡評価を追跡する','Trace early returns and short-circuit evaluation')],
sections:[
s(b('状態を条件で分ける','Branch according to state'),[
b('ifは条件と二つの選択肢を持ちます。whenは真のときだけ複数の式を実行し、unlessは偽のときだけ実行します。condは上から最初に真になる節を選びます。jump-bodyのcondは、まず接地中の通常ジャンプを試し、そうでなければ壁キックの条件を調べます。この順序が、地上で壁に触れていても通常ジャンプになる理由です。','if chooses between two alternatives. when runs several expressions only when a condition is true; unless does so when it is false. cond selects the first true clause from top to bottom. jump-body first handles a grounded jump, then checks for a wall kick. This order is why touching a wall while grounded still produces a normal jump.'),
b('caseは既知の値による分岐です。武器番号0〜3やキーワード:healthには自然ですが、距離が9未満かなどの比較にはcondを使います。caseのキーは通常の式として評価される一方、各節のキーは比較用のデータです。tは最後の既定節によく使います。','case dispatches on a known value. It fits weapon indexes 0–3 or the keyword :health; comparisons such as distance < 9 belong in cond. The case key expression is evaluated, while clause keys are comparison data. t is commonly used for the final default clause.')],
'(defun life-state (hp shield)\n  (cond ((<= hp 0) :dead)\n        ((> shield 0) :protected)\n        (t :alive)))\n\n(case :rail\n  (:health 35)\n  (:rail 8)\n  (t 0))'),
s(b('集合と回数と継続条件','Iterate a collection, a count, or a condition'),[
b('dolistはリストの要素、dotimesは0から指定回数未満までの整数、loopはより広い反復を扱います。dotimesのiは0から始まるので、4種類の武器は0・1・2・3です。dolistの引数リスト末尾に結果の式を置くと、反復が終わった時にその式を返します。floor-atの(dolist (b *blocks* y) …)は計算した高さyを返す例です。','dolist iterates list elements, dotimes iterates integers from 0 up to but excluding a count, and loop handles more general iteration. dotimes starts at 0, so four weapons have indexes 0, 1, 2, 3. A result expression at the end of dolist’s binding list is evaluated when iteration finishes. floor-at’s (dolist (b *blocks* y) …) returns the computed height.'),
b('loopのcollectは結果リストを作り、sumは合計を求め、whileは継続条件です。mainの固定刻みループはaccumulatorが+tick+以上である間だけ動きます。「何回で終わるか」「毎回何が変わるか」を確認しないと無限ループができます。とくにwhileの条件を変えるdecfを忘れないでください。','loop’s collect builds a result list, sum computes a total, and while supplies a continuation condition. main’s fixed-step loop runs while accumulator is at least +tick+. Always identify how the loop ends and what changes on each iteration. Forgetting the decf that changes a while condition can create an infinite loop.')],
"(loop for i below 4 collect i) ; => (0 1 2 3)\n(dolist (kind '(:health :rail))\n  (format t " + '"~A~%"' + " kind))\n(let ((remaining 3))\n  (loop while (plusp remaining) do (decf remaining))\n  remaining)"),
s(b('危険な式を評価しない','Avoid evaluating a dangerous expression'),[
b('andとorは左から短絡評価し、真偽だけでなく最後に調べた値を返します。(and target (actor-hp target))ならtargetがNILのとき、actor-hpは呼ばれません。これはnull参照を防ぐ実用的な書き方です。反対に、全処理を必ず実行したい場合はandへ副作用を隠さずprognで順に書きます。','and and or short-circuit from left to right and return values, not just Boolean flags. In (and target (actor-hp target)), actor-hp is not called when target is NIL. That is a useful way to guard a missing object. If all effects must occur, put them in progn rather than hiding them in and.'),
b('return-fromは関数の暗黙のblockから抜けます。単独のreturnは通常、loopやdolistなどのNILという名前のblockから抜けます。両者を混同すると、探索を終えたつもりで内側の反復しか終わっていない、というバグになります。','return-from exits the named implicit block of a function. A plain return commonly exits the NIL-named block established by loop or dolist. Confusing them can end only an inner iteration when you intended to end the entire search.')],
'(defun first-positive (numbers)\n  (dolist (n numbers)\n    (when (plusp n)\n      (return-from first-positive n)))\n  nil)\n(first-positive \'(-4 0 7 2)) ; => 7')],
sources:[source('arena.lisp','jump-body','collect-pickup'),source('main.lisp','main')],
exercise:ex(b('弾数が正で、クールダウンが0以下で、生存中のときだけ:fireを返すcan-fireを書いてください。','Write can-fire so it returns :fire only with positive ammo, nonpositive cooldown, and positive HP.'),b('三つの条件と結果をandで並べます。','Put the three conditions and the result in and.'),'(defun can-fire (ammo cooldown hp)\n  (and (> ammo 0) (<= cooldown 0) (> hp 0) :fire))',b('結果は:fireまたはNILです。条件に数をそのまま渡すと0も真なので、比較は省略しません。','The result is :fire or NIL. Explicit comparisons matter because passing a number directly treats 0 as true.')),
quiz:q(b('(and nil (/ 1 0))は何を返す？','What does (and nil (/ 1 0)) return?'),[b('NIL','NIL'),b('必ずゼロ除算','Always a division error'),b('T','T')],0,b('最初のNILで短絡するため、ゼロ除算の式は評価されません。','Evaluation stops at the first NIL, so the division is never evaluated.')),
test:'(assert (null (and nil (/ 1 0))))\n(defun can-fire (ammo cooldown hp) (and (> ammo 0) (<= cooldown 0) (> hp 0) :fire))\n(assert (eq (can-fire 12 0 100) :fire))\n(assert (null (can-fire 0 0 100)))\n(assert (equal (loop for i below 4 collect i) \'(0 1 2 3)))'
},
{
id:'vectors',part:1,minutes:65,title:b('ベクトルで、動きを語る','Speak about motion with vectors'),
subtitle:b('x・y・zを、三つのばらばらな数字から一つの意味へ。','Turn x, y, and z from three separate numbers into one meaningful value.'),
goals:[b('defstructで位置と速度を表現する','Represent position and velocity with defstruct'),b('加算・スケール・内積・正規化を実装する','Implement addition, scaling, dot products, and normalization'),b('ゼロベクトルと共有参照を扱う','Handle zero vectors and shared references')],
sections:[
s(b('構造体が作る、小さな語彙','A structure creates a vocabulary'),[
b('defstructはデータ型と、構築・読み取り・変更用の関数をまとめて作ります。このゲームのvは(v 1 2 3)で構築でき、v-x、v-y、v-zで成分を読みます。通常のmake-vではなくvを使うのは、:constructorオプションを指定しているためです。setfは生成されたアクセサにも使えます。','defstruct creates a data type together with construction and access operations. The game builds v with (v 1 2 3) and reads components using v-x, v-y, and v-z. It uses v rather than the usual make-v because of the :constructor option. The generated accessors are also setf places.'),
b('座標系はyが上、地面がx–z平面、正面が基本的に-zです。位置はメートル相当、速度は毎秒の移動量、dtは秒で揃えます。同じ三成分でも位置と速度は意味が異なります。位置を二倍しても「速く走る」設定にはなりません。単位をコメントや変数名で意識してください。','The coordinate system has y upward, the ground in the x–z plane, and the initial forward direction along -z. Use consistent units: meter-like world distances, distance per second for velocity, and seconds for dt. Position and velocity may both have three components, but they mean different things. Doubling a position does not make a runner faster.')],
'(defstruct (v (:constructor v (x y z)))\n  x y z)\n(let ((position (v 1 2 3)))\n  (setf (v-y position) 4)\n  (v-y position)) ; => 4'),
s(b('長さ、方向、移動量','Length, direction, and displacement'),[
b('v+は成分ごとの加算、v*は各成分のスケールです。内積dot3(a,b)はax×bx＋ay×by＋az×bz。自分自身との内積の平方根が長さです。unitは長さで割って、長さ1の方向を作ります。斜め入力(1,0,1)を正規化すると約(0.707,0,0.707)になり、斜めだけ速くなる問題を防げます。','v+ adds corresponding components and v* scales them. dot3(a,b) is ax×bx + ay×by + az×bz. The square root of a vector’s dot product with itself gives its length. unit divides by that length to create a unit direction. Normalizing diagonal input (1,0,1) gives approximately (0.707,0,0.707), avoiding a diagonal-speed advantage.'),
b('長さ0で割るとエラーになります。unitは長さが0.00001未満ならゼロを返します。これは何も押していない入力にも対応するためです。flatはyを0にして水平速度だけを取り出します。速度表示と最高速度制限は、ジャンプの縦速度を水平移動へ混ぜないようflatを使います。','Dividing by zero is an error. unit returns a zero vector when length is below 0.00001, which handles input with no keys held. flat sets y to 0 so horizontal speed can be considered separately. The HUD and speed cap use flat to avoid counting jump velocity as horizontal movement.')],
'(defun dot3 (a b)\n  (+ (* (v-x a) (v-x b))\n     (* (v-y a) (v-y b))\n     (* (v-z a) (v-z b))))\n(defun len (a) (sqrt (dot3 a a)))\n(defun unit (a)\n  (let ((n (len a)))\n    (if (< n 0.00001) (v 0 0 0) (v* a (/ n)))))','vectors'),
s(b('参照を共有するか、新しく作るか','Share a reference or create a new value'),[
b('(let ((b a)) …)はaの指す構造体を複製しません。b経由でv-xをsetfするとaから見える値も変わります。一方、このゲームのv+、v-、v*は新しいvを返します。純粋な計算を新しい値で表すと、中間結果が勝手に旧位置を書き換える問題を減らせます。','(let ((b a)) …) does not copy the structure referenced by a. Setting v-x through b changes the same object visible through a. In contrast, the game’s v+, v-, and v* return fresh v structures. Returning a new value for a calculation helps avoid intermediate results accidentally overwriting the old position.'),
b('ただし、新しいオブジェクトを大量に作ると割り当てとGCの費用がかかります。まず読みやすく正しい計算を作り、実測してから、頻繁な更新だけを再利用可能なベクトルへ変えます。ここで速さのために全データを破壊的に変えると、衝突判定の旧位置が消える方が大きな問題です。','Creating many fresh objects costs allocation and garbage collection. Start with clear, correct calculations, measure, then reuse vectors only where frequent updates justify it. Making everything destructive too early can lose the old position that collision detection needs—a larger problem than the allocation you tried to save.')])],
sources:[source('arena.lisp','v+','v*','dot3','unit','flat','direction')],
exercise:ex(b('位置(1,0,2)、速度(12,0,-6)、dt=1/120から次の位置を求め、旧位置が変わっていないこともassertしてください。','Compute the next position from (1,0,2), velocity (12,0,-6), and dt = 1/120. Assert that the old position is unchanged.'),b('v+とv*を組み合わせます。','Combine v+ and v*.'),'(let* ((p (v 1 0 2))\n       (velocity (v 12 0 -6))\n       (next (v+ p (v* velocity 1/120))))\n  (assert (= (v-x next) 11/10))\n  (assert (= (v-z next) 39/20))\n  (assert (= (v-x p) 1)))',b('移動量を速度そのものと混同しないことと、計算が入力オブジェクトを変更しないことを同時に確認します。','This checks both the distinction between velocity and displacement and the absence of mutation to the input.')),
quiz:q(b('正規化した(1,0,1)の長さは？','What is the length of normalized (1,0,1)?'),[b('約1','Approximately 1'),b('2','2'),b('0','0')],0,b('各成分は約0.707になり、二乗和の平方根が1になります。','Each nonzero component becomes approximately 0.707; the square root of their squared sum is 1.')),
test:'(let* ((p (v 1 0 2)) (next (v+ p (v* (v 12 0 -6) 1/120)))) (assert (= (v-x next) 11/10)) (assert (= (v-z next) 39/20)) (assert (= (v-x p) 1)))\n(assert (< (abs (- (len (unit (v 1 0 1))) 1)) 0.00001))\n(assert (= (len (unit (v 0 0 0))) 0))',model:true
}
];
