import {b,s,ex,q,source,type Chapter} from './content.ts';
export const engineChapters: Chapter[] = [
{
id:'time',part:2,minutes:65,title:b('世界に、同じ一秒を流す','Give the world a consistent second'),
subtitle:b('描画回数をゲームの速さにしない。','Do not let the rendering rate determine the speed of the game.'),
goals:[b('位置・速度・加速度と単位を理解する','Understand position, velocity, acceleration, and their units'),b('固定刻みとaccumulatorを実装する','Implement a fixed step and an accumulator'),b('入力・更新・描画を分離する','Separate input, simulation, and rendering')],
sections:[
s(b('一フレームは、一秒ではない','A frame is not a unit of time'),[
b('毎フレーム位置を0.1ずつ増やすと、30 FPSでは毎秒3、144 FPSでは毎秒14.4進みます。正しい単位は「速度×秒」です。重力は毎秒の速度変化なので、まずvy -= gravity×dtで速度を更新し、次にy += vy×dtで位置を更新します。ゲームはこの順の半陰的Euler積分を使います。解析解と完全一致はしませんが、刻みを固定すれば比較可能になります。','Adding 0.1 to position per rendered frame moves 3 units per second at 30 FPS and 14.4 at 144 FPS. Use velocity multiplied by seconds. Gravity changes velocity per second: first vy -= gravity×dt, then y += vy×dt. This is semi-implicit Euler integration. It is not identical to the analytic solution, but a fixed step makes runs comparable.'),
b('このゲームの+tick+は1/120秒。描画は機械の速度で変わりますが、更新は常に同じ刻みです。入力は描画側で一度読み、必要な更新へ同じ値を渡します。Spaceの「押した瞬間」はjump-bufferに短く保存し、描画フレームと物理更新の境目で失わないようにします。','The game’s +tick+ is 1/120 second. Rendering rate may vary, but simulation uses that same interval. Read input once per rendered frame and pass it to the required updates. A Space press is briefly stored in jump-buffer so it is not lost between a rendered frame and a physics step.')],
'(let ((position 0.0) (velocity 12.0) (dt (/ 1.0 120)))\n  (dotimes (i 120)\n    (incf position (* velocity dt)))\n  position) ; approximately 12.0','timestep'),
s(b('余った時間を捨てずに持つ','Keep the remaining fraction of time'),[
b('accumulatorへ描画間隔dtを足します。1/120秒以上たまっている間tick-gameを呼び、呼ぶごとに1/120秒を引きます。例えば1/60秒なら2回、1/144秒なら0回のフレームと1回のフレームが混ざります。端数は次へ残します。これにより、整数回の更新を無理に丸めて時間を失うことを防げます。','Add each rendered frame’s dt to an accumulator. While it holds at least 1/120 second, call tick-game and subtract one step. A 1/60-second frame needs two updates; at 1/144 second, some frames need none and some need one. Carry the remainder forward rather than rounding it away.'),
b('長時間停止した直後に何千回も更新すると、追いつくためにまた停止する悪循環が起きます。mainはフレームdtを0.1秒に制限し、ポーズ時はaccumulatorを0へ戻します。これは停止時間中の試合を完全に再現する仕様ではありません。停止から操作へ安全に戻るための選択です。オンラインゲームなら時間同期の設計は別に必要です。','Updating thousands of times after a long stall can create a spiral of trying to catch up and stalling again. main caps frame dt at 0.1 second and resets the accumulator while paused. This does not reproduce every second of a stall; it prioritizes returning to interactive play. Online games require a separate synchronization design.')],
'(incf accumulator dt)\n(loop while (>= accumulator +tick+) do\n  (tick-game +tick+ wish fire jump-held)\n  (decf accumulator +tick+))'),
s(b('関数の順序が、ゲームの順序','Function order becomes game order'),[
b('tick-gameはタイマーを減らし、死者の復活または生者の移動を処理し、ロケットとアイテムを更新して、試合終了を判定します。render-frameはその結果を描きます。描画の中でダメージを与えると、画面を見ないテストでは戦闘が起きなくなります。画面なしで120秒のbot戦を回せるのは、更新が描画から独立しているためです。','tick-game updates timers, respawns dead actors or moves living ones, advances rockets and pickups, then checks match completion. render-frame draws that resulting state. If damage were applied during drawing, a headless test would not produce combat. A 120-second bot simulation works without a screen because updating is independent of rendering.'),
b('固定刻みだけで完全な決定性は得られません。乱数のseed、actorの更新順、浮動小数点、入力列も揃える必要があります。再現テストではseed-random-stateで乱数を固定しています。実験室は時間刻みの効果を示す数値モデルで、ゲーム全体のリプレイではありません。','A fixed step alone does not make a game fully deterministic. Random seed, actor order, floating-point behavior, and the input sequence also matter. The reproducible test fixes randomness using seed-random-state. The lab illustrates time stepping; it is not a replay of the complete game.')])],
sources:[source('arena.lisp','tick-game','update-timers'),source('main.lisp','main')],
exercise:ex(b('描画間隔1/30秒を30回受け取り、1/120秒の更新が120回になるaccumulatorを書いてください。','Write an accumulator that receives 30 frames of 1/30 second and performs 120 updates of 1/120 second.'),b('この計算だけは有理数で行うと端数比較が正確です。','Use rational numbers in this isolated experiment to make remainder comparisons exact.'),'(let ((accumulator 0) (ticks 0))\n  (dotimes (frame 30)\n    (incf accumulator 1/30)\n    (loop while (>= accumulator 1/120) do\n      (incf ticks) (decf accumulator 1/120)))\n  (assert (= ticks 120)))',b('実ゲームは単精度を使うため、細部の丸めが存在します。ここではアルゴリズムの意図を正確な数で確かめます。','The real game uses single precision and has rounding details. This experiment verifies the algorithm’s intent with exact numbers.')),
quiz:q(b('144 FPSで毎フレーム1回、常に1/120秒更新すると？','What happens if a 144 FPS renderer performs one 1/120-second update every frame?'),[b('実時間と一致する','It matches real time'),b('ゲームが実時間より速く進む','The simulation runs faster than real time'),b('描画だけが暗くなる','Only rendering becomes darker')],1,b('毎秒144×1/120=1.2秒分進みます。描画回数と更新回数を同じにしないことが重要です。','It simulates 144×1/120 = 1.2 seconds per real second. Render counts and simulation counts must be separated.')),
test:'(let ((accumulator 0) (ticks 0)) (dotimes (frame 30) (incf accumulator 1/30) (loop while (>= accumulator 1/120) do (incf ticks) (decf accumulator 1/120))) (assert (= ticks 120)))'
},
{
id:'native-window',part:2,minutes:75,title:b('Lispの世界を、画面へつなぐ','Connect Lisp’s world to a real window'),
subtitle:b('境界を薄くして、ゲームの意味をLisp側に残す。','Keep the boundary thin and the meaning of the game in Lisp.'),
goals:[b('FFIとABIの違いを理解する','Distinguish an FFI from an ABI'),b('DLLを読み、ウィンドウを描く','Load the DLL and draw a window'),b('資源の終了処理を保証する','Guarantee resource cleanup')],
sections:[
s(b('外国語の関数を呼ぶ','Call functions across a language boundary'),[
b('FFIはForeign Function Interface、別の言語で作った関数を呼ぶ仕組みです。ABIは引数や戻り値を機械レベルでどう渡すかの約束です。raylibのVector3やColorをそのままLispから渡すと、構造体の配置と渡し方を正しく扱う必要があります。bridge.cはss_box(x,y,z,w,h,d,color)のような平坦な引数へ変えて、その負担をC側へ寄せます。','An FFI is a mechanism for calling functions made in another language. An ABI specifies how arguments and results are passed at the machine level. Passing raylib’s Vector3 or Color directly requires correct structure layout and calling conventions. bridge.c exposes flat arguments such as ss_box(x,y,z,w,h,d,color), keeping those layout details on the C side.'),
b('SBCLのsb-alien:define-alien-routineで型を宣言します。Cのfloatにはsingle-float、intにはint、文字列にはc-stringを対応させます。64ビットの処理系とDLLを揃え、色の#xRRGGBBAAは符号なし整数で渡します。型宣言を間違えると普通のLispの型エラーではなく、ネイティブ側のメモリ破壊になることがあります。','Declare types with SBCL’s sb-alien:define-alien-routine. Map C float to single-float, int to int, and text to c-string. Match the runtime and DLL bitness; pass #xRRGGBBAA colors as unsigned integers. A wrong declaration can corrupt native memory rather than produce an ordinary Lisp type error.')],
'(sb-alien:define-alien-routine\n    ("ss_init" raw-init) sb-alien:void\n  (width sb-alien:int)\n  (height sb-alien:int))\n\n; The game uses the native macro to generate this boundary.\n(native ss-init void (w int) (h int))'),
s(b('最小のウィンドウを作る','Build the smallest visible milestone'),[
b('先にgame/build.ps1でarena.dllをビルドします。workshop/09-native-window.lispはplatform.lispだけを読み、DLLをロードし、黒い背景へ文字を描きます。完成ゲームのmainを呼びません。ウィンドウの×で終了してください。この小さな到達点なら、まだ物理やbotのバグを疑う必要がありません。','Build arena.dll with game/build.ps1 first. workshop/09-native-window.lisp loads only platform.lisp and the DLL, then draws text over a dark background. It does not call the finished game’s main. Close it with the window’s ×. This small milestone isolates the platform from physics and bot bugs.'),
b('ss-beginとss-endの間で描画し、ss-cameraとss-2dの間で3Dを描きます。unwind-protectは正常終了でもエラーでも後片付けを実行します。ウィンドウ、音声、フォント、モデル、シェーダーは終了時に解放します。プロセスが死ねばOSが回収するから、と終了処理を省くと再起動や開発時の問題を見失います。','Draw between ss-begin and ss-end; draw 3D between ss-camera and ss-2d. unwind-protect executes cleanup on both normal completion and errors. Release the window, audio, font, model, and shader at shutdown. Relying only on process termination hides problems during repeated development runs.')],
'(ss-init 960 600)\n(unwind-protect\n    (loop until (plusp (ss-quit)) do\n      (ss-input)\n      (ss-begin)\n      (ss-text "Hello, Lisp arena" 40 40 28 #x4AE5DAFF)\n      (ss-end))\n  (ss-close))'),
s(b('失敗を、層ごとに診断する','Diagnose failure by layer'),[
b('DLLがないならビルド先を確認します。DLLはあるのにロードできないなら、64ビットの一致と依存ライブラリを確認します。表示できるが黒いだけなら、描画順、カメラ、色、シェーダーを確認します。nativeマクロは浮動小数点トラップをC側の通常の方針に合わせて一時的にマスクしますが、Lispの計算全体のエラーを隠すものではありません。','If the DLL is missing, inspect its build path. If it exists but cannot load, check bitness and dependent libraries. If the window is present but blank, check drawing order, camera, color, and shader. The native macro temporarily masks floating-point traps to follow the usual C policy; it does not hide errors throughout Lisp gameplay.'),
b('境界で何を担当するかを固定します。C側は描画と音声と入力、Lisp側は位置とルール。ダメージ計算をCの描画関数へ足すと、二つの場所を読まないと仕様が分からなくなります。Cを小さく保つ理由は「Lisp純度」ではなく、どこを変えれば動作が変わるかを明確にすることです。','Keep the boundary’s responsibility fixed: C handles drawing, audio, and input; Lisp handles positions and rules. Adding damage calculation to a C drawing function makes behavior depend on two locations. Keeping C small is about knowing where a behavior lives, not about language purity.')])],
sources:[source('platform.lisp','native'),source('native/bridge.c')],
exercise:ex(b('最小ウィンドウの文字色を金色へ変え、別の位置へ二行目を描いてください。終了処理は残します。','Change the minimal window’s text to gold and draw a second line at a different position. Keep the cleanup.'),b('色は#xRRGGBBAAです。最後のFFは不透明。','Color is #xRRGGBBAA. The final FF is opaque.'),'(ss-text "LISP ATELIER" 40 40 28 #xD7B879FF)\n(ss-text "I can draw from Common Lisp." 40 90 20 #xEAF0F7FF)',b('実験は描画だけを変えます。成功条件は二行が見えて、×でプロセスが正常に終了することです。','This experiment changes presentation only. Success means both lines are visible and closing the window exits normally.')),
quiz:q(b('Lispが64ビットなら、読み込むarena.dllは？','For a 64-bit Lisp runtime, what should arena.dll be?'),[b('32ビットでも常に使える','32-bit always works'),b('同じ64ビット向け','Built for the same 64-bit architecture'),b('HTMLファイルへ改名する','An HTML file renamed as a DLL')],1,b('同一プロセスへロードするネイティブライブラリのアーキテクチャを揃えます。','A native library loaded into the same process must match its architecture.')),
test:'(assert (fboundp \'ss-init))\n(assert (fboundp \'ss-camera))',model:true
},
{
id:'world',part:2,minutes:70,title:b('地図を、データで建てる','Build an arena from data'),
subtitle:b('見える形と、ぶつかる形を同じ世界へ置く。','Put visible geometry and collision geometry in the same world.'),
goals:[b('中心とサイズから箱の範囲を求める','Derive box bounds from a center and size'),b('floor-atで高さを問い合わせる','Query world height with floor-at'),b('小さな描画マイルストーンを作る','Create a small rendering milestone')],
sections:[
s(b('箱一つに必要な情報','What a box needs'),[
b('solid構造体は中心pos、サイズsize、色、アクセント色を持ちます。名前をblockにしないのはCommon LispのBLOCKと衝突するためです。:conc-name block-を指定して、アクセサはblock-posのようにしています。中心(0,0.6,0)、サイズ(7,1.2,7)の箱は、上面がy=1.2、底面がy=0になります。','The solid structure stores center, size, color, and accent color. It is not named block because that conflicts with Common Lisp’s BLOCK. :conc-name block- still produces accessors such as block-pos. A box centered at (0,0.6,0) with size (7,1.2,7) has its top at y=1.2 and bottom at y=0.'),
b('最小座標は中心−サイズ/2、最大座標は中心＋サイズ/2です。in-footprintはx–z平面に位置が含まれるかを判定します。make-arenaは箱とアイテムの配置をデータとして積み上げ、最後に経路探索グラフを構築します。左右対称の形はsideが-1と1のdolistで生成し、同じ地図の重複コードを減らします。','Minimum bounds are center minus half-size; maximum bounds are center plus half-size. in-footprint tests x–z coverage. make-arena builds boxes and item placements as data, then creates navigation. Symmetric geometry is generated with side = -1 and 1 in a dolist, reducing repeated map code.')],
'(add-block 0 0.6 0 7 1.2 7 #x6A6872FF #xB78BFFFF)\n(box-min (first *blocks*))\n(box-max (first *blocks*))'),
s(b('地面は、単なるy=0ではない','The ground is more than y = 0'),[
b('floor-atは指定したx,zを含む箱の上面を調べ、below以下で最も高い面を返します。belowがあるので、頭上の足場へ勝手に瞬間移動しません。初期配置では高い上面を探し、移動では現在の高さ＋小さな段差までを探します。足場の上、地面、階段で同じ問い合わせを使えます。','floor-at examines tops of boxes covering x,z and returns the highest surface no higher than below. That bound prevents teleporting onto overhead platforms. Spawn placement queries the highest surface; movement queries up to current height plus a small step allowance. The same query handles ground, terraces, and stairs.'),
b('階段は少しずつ高くなる細い箱の列です。段差0.3125は自動乗り越えの0.36未満であり、数値が対応しています。片方だけ変えると、見た目は階段でもプレイヤーは登れなくなります。地図改造では形の値だけでなく、衝突とbotの段差制限との関係を確認してください。','Stairs are a sequence of thin boxes with increasing heights. The 0.3125 step height is below the 0.36 automatic step allowance. Those numbers work together. Changing only one can create stairs that look usable but cannot be climbed. Map changes need collision and bot climb limits checked as well.')],
'(make-arena)\n(floor-at 0 0)   ; => 1.2, central altar\n(floor-at 22 0)  ; => 3.2, side terrace\n(floor-at 0 24)  ; => 5.0, upper terrace'),
s(b('最初の3D風景を描く','Draw your first 3D scene'),[
b('workshop/10-world-window.lispは、ゲームの地図モデルを読み、カメラから箱だけを描きます。actorや武器や試合はまだ動きません。カメラの位置と、そこから見る方向を独立に考えます。視線方向は単位ベクトル、画角は視野の広さです。ここで地図が見えれば、次章からは描画の前に物理を計算するだけです。','workshop/10-world-window.lisp loads the map model and draws its boxes from a camera. Actors, weapons, and matches are not moving yet. Treat camera position and viewing direction separately. The view direction is a unit vector; the field of view controls its spread. Once this milestone works, the next stage can compute physics before drawing.'),
b('実ゲームのrender-arenaは箱の描画に、縁の発光、床の目地、パッド、背景の建物を足します。装飾は必ずしも衝突する形ではありません。太い装飾を通路へ置くなら、見えない障害物や見えるのに通れる壁にならないよう、solidへの追加も判断します。','render-arena adds glowing edges, floor seams, launch pads, and background buildings. Decoration is not necessarily collision geometry. If you put a substantial visual object into a passage, decide whether it also needs a solid so the game does not produce invisible obstacles or walk-through walls.')])],
sources:[source('arena.lisp','add-block','box-min','box-max','floor-at','make-arena'),source('view.lisp','render-arena')],
exercise:ex(b('中心(5,1,0)、サイズ(2,2,4)の箱を追加し、上面が2になることを確認します。変更は完成マップの複製で行ってください。','Add a box centered at (5,1,0) with size (2,2,4), and verify that its top is 2. Experiment on a copy of the map.'),b('floor-atへ箱の中心のx,zを渡します。','Query floor-at at the box center’s x,z.'),'(let ((*blocks* nil))\n  (add-block 5 1 0 2 2 4)\n  (assert (= (floor-at 5 0) 2))\n  (assert (= (floor-at 10 0) 0)))',b('地図の外にある座標では基準の床0を返します。このゲームの地面モデルは穴のある地形全体を扱う汎用物理ではありません。','A location outside the box returns the base floor 0. This is a specific arena-floor model, not a general terrain system with arbitrary holes.')),
quiz:q(b('中心y=1、箱の高さ2なら、上面のyは？','With center y = 1 and height 2, what is the top y?'),[b('1','1'),b('2','2'),b('3','3')],1,b('中心に半分の高さを足します。箱の高さ全部を足しません。','Add half the height to the center, not the full height.')),
test:'(let ((*blocks* nil)) (add-block 5 1 0 2 2 4) (assert (= (floor-at 5 0) 2)) (assert (= (floor-at 10 0) 0)))',model:true
},
{
id:'collision',part:2,minutes:80,title:b('走る、止まる、階段を登る','Run, stop, and climb a stair'),
subtitle:b('位置を変える前に、「そこへ行けるか」を問う。','Before changing position, ask whether the proposed position is possible.'),
goals:[b('加速と摩擦を実装する','Implement acceleration and friction'),b('候補位置による衝突を理解する','Understand collision using a candidate position'),b('床・天井・段差を別々に処理する','Handle floors, ceilings, and steps separately')],
sections:[
s(b('入力は位置ではなく、意図','Input expresses intent, not a position'),[
b('player-inputはWASDからwishという単位方向を作ります。accelerateは現在の水平速度をwishへ内積で投影し、目標速度12までの不足分を足します。地上の加速度95、空中22は同じではありません。空中では既存の勢いを残して方向を変えられるため、アリーナFPSらしい操作感になります。','player-input turns WASD into a unit wish direction. accelerate projects current horizontal velocity onto wish with a dot product, then adds only what is missing toward a target speed of 12. Ground acceleration 95 differs from air acceleration 22. Air movement can redirect existing momentum, which produces an arena-FPS feel.'),
b('接地していてジャンプを要求していない時だけ摩擦を掛けます。保持ジャンプで接地した瞬間に跳べば、地上摩擦による減速を避けられます。水平速度は32に制限します。値を変える前に「目標速度」「加速」「最大速度」「摩擦」を別の仕様として扱ってください。一つのspeed変数では全部を表せません。','Friction applies only when grounded and no jump is requested. Holding jump can trigger a hop on landing before ground friction removes momentum. Horizontal speed is capped at 32. Treat target speed, acceleration, maximum speed, and friction as separate rules; a single speed variable cannot represent all four.')],
'; Project velocity onto the intended direction.\n(let* ((current (dot3 (flat velocity) wish))\n       (add (min (max 0 (- 12 current))\n                 (* (if ground 95 22) dt))))\n  (incf (v-x velocity) (* (v-x wish) add))\n  (incf (v-z velocity) (* (v-z wish) add)))'),
s(b('衝突は、候補を承認する処理','Collision approves or rejects a proposal'),[
b('move-bodyはx方向、z方向を分けて候補位置を作ります。blockedなら、その軸の移動を取り消し、軸方向の速度を0にします。片方が壁に阻まれても、もう片方は更新できるので壁に沿って滑れます。body-overlapsは半径0.42と高さ1.8のプレイヤーを、箱の範囲との重なりで近似します。','move-body proposes x and z motion separately. If blocked, it rejects that axis and zeroes its velocity. The other axis can still move, producing wall sliding. body-overlaps approximates a player with radius 0.42 and height 1.8 by overlap against box bounds.'),
b('この近似は厳密なカプセル形状ではなく、水平の箱拡張に近い判定です。120 Hzと速度上限は一更新の移動量を小さくしますが、あらゆる薄い障害物への連続衝突を保証しません。非常に速いダッシュを追加するなら、移動の分割かswept collisionが必要か検証してください。','This is not an exact capsule test; horizontally it resembles expanded box bounds. The 120 Hz step and speed cap keep per-step movement small, but they do not guarantee continuous collision with every thin obstacle. A much faster dash may need smaller movement substeps or swept collision.')],
'; Sketch of one-axis movement, not a replacement for move-body.\n(if (blocked candidate)\n    (setf (v-x velocity) 0)\n    (setf p candidate))'),
s(b('三つの高さの扱い','Three kinds of vertical behavior'),[
b('地上で小さな段差に阻まれたときは、候補を0.36上げて空いているか試します。下降中に床を通り越す候補なら床へ位置を戻し、vyを0、groundをTにします。上昇中に天井へぶつかる候補ならvyを0にします。床へ落ちる処理と、上へジャンプする処理を同じ条件にまとめると、天井を床として扱うバグが起きます。','When a grounded actor meets a small step, movement tries the candidate 0.36 units higher. If descending motion would cross a floor, set position to the floor, vy to 0, and ground to T. If rising motion hits a ceiling, zero vy. Combining these into one broad condition can accidentally treat a ceiling as a floor.'),
b('通常ジャンプはvyを10.2へ設定し、groundをNILへ変えます。重力28で理論上の上昇高さは10.2²/(2×28)≈1.86です。半陰的積分では少し差が出ます。ジャンプ力を変える時は、到達できる足場、botの上昇制限、壁キックとの差も一緒に確認します。','A normal jump sets vy to 10.2 and ground to NIL. With gravity 28, the analytic rise is 10.2²/(2×28) ≈ 1.86; semi-implicit integration gives a slightly different result. A jump-strength change also affects reachable platforms, bot climb limits, and the distinction from a wall kick.')])],
sources:[source('arena.lisp','accelerate','body-overlaps','blocked','move-body')],
exercise:ex(b('壁へ120更新走っても通り抜けないテストを書き、速度を32から80へ変える前に同じテストを実行します。','Write a test that runs into a wall for 120 updates without passing through, and run it before increasing a speed cap from 32 to 80.'),b('x=-27.5、z=15は外周の内側です。','x = -27.5, z = 15 lies just inside the perimeter.'),'(make-arena)\n(let ((a (make-actor :pos (v -27.5 0 15))))\n  (dotimes (i 120)\n    (accelerate a (v -1 0 0) +tick+))\n  (assert (>= (v-x (actor-pos a)) -27.59)))',b('外周の一ケースが通るだけで全衝突の保証にはなりません。角、薄い壁、階段、空中でも別の境界条件を確認します。','Passing this perimeter case is not a proof of all collision behavior. Also test corners, thin walls, stairs, and airborne movement.')),
quiz:q(b('xとzを別々に解決することで得られる動きは？','What behavior is helped by resolving x and z separately?'),[b('壁沿いに滑る','Sliding along a wall'),b('無限弾薬','Infinite ammunition'),b('自動的なネット同期','Automatic network synchronization')],0,b('一方の軸が止まっても、壁に平行な軸の移動を残せます。','One axis can stop while motion parallel to the wall remains.')),
test:'(make-arena)\n(let ((a (make-actor :pos (v -27.5 0 15)))) (dotimes (i 120) (accelerate a (v -1 0 0) +tick+)) (assert (>= (v-x (actor-pos a)) -27.59)))',model:true
},
{
id:'wall-kick',part:2,minutes:70,title:b('壁を、移動の味方にする','Turn a wall into an ally'),
subtitle:b('法線、入力バッファ、クールダウンから壁キックを組み立てる。','Build a wall kick from a normal, an input buffer, and a cooldown.'),
goals:[b('壁の法線を読み取る','Read a wall normal'),b('壁キックの速度を計算する','Compute wall-kick velocity'),b('連続発動と外周逸脱を防ぐ','Prevent repeated triggering and perimeter escape')],
sections:[
s(b('法線は、壁から離れる方向','A normal points away from the wall'),[
b('法線は面に垂直な方向です。アリーナの箱なら左右の面は(±1,0,0)、前後の面は(0,0,±1)。wall-normalは縦方向が重なる箱だけを調べ、プレイヤーの横にある最も近い面を探します。距離0.82までが壁キック候補です。壁の上面へ法線を出さないのは、床の通常ジャンプと役割を分けるためです。','A normal is perpendicular to a surface. Arena box side normals are (±1,0,0) and (0,0,±1). wall-normal considers vertically overlapping boxes and finds a nearby side face within 0.82. It does not use the top face, keeping a wall kick separate from an ordinary floor jump.'),
b('距離dは面の向きsideを掛けて外側が正になるように計算します。0<=d<=bestで候補を更新します。面の内側に深くいる点を近い壁として採用しないことが重要です。角では複数候補があるため、最も近い面を選ぶルールを使っています。','The signed distance d is multiplied by side so points outside the face are positive. A candidate satisfies 0 <= d <= best. This avoids treating a deeply embedded point as a valid nearby wall. At a corner, the nearest-face rule resolves multiple candidates.')]),
s(b('勢いを、意図した向きへ作り直す','Construct momentum in a deliberate direction'),[
b('空中でSpaceが要求され、wall-coolが0以下で、法線が得られたときに発動します。水平速度はnormal×16＋wish×4。上向き速度は11.5です。これは旧速度への加算ではなく、水平成分を新しいpushで置き換える仕様です。壁へ向いたwishなら反発が少し弱まり、壁から離れるwishなら強まります。','Trigger while airborne when Space is requested, wall-cool is nonpositive, and a wall normal exists. Horizontal velocity becomes normal×16 + wish×4, and upward velocity becomes 11.5. This replaces the horizontal components rather than adding to the old velocity. Intent toward the wall reduces the push; intent away increases it.'),
b('発動後はwall-coolを0.24秒、jump-bufferを0へ設定します。次の120 Hz更新で同じ要求がまた発動しないようにするためです。壁キック回数、音、HUDの短い通知も同じ出来事で更新しますが、物理が先、見せ方が後です。図ではx–y軌跡を描き、z成分は数値で確認します。','After triggering, set wall-cool to 0.24 second and jump-buffer to 0. This prevents the same request from firing again on the next 120 Hz step. A kick counter, sound, and short HUD notice accompany the event, but physics comes before presentation. The lab plots the x–y trajectory and reports z separately.')],
'(let ((push (v+ (v* normal 16) (v* wish 4))))\n  (setf (v-x (actor-vel a)) (v-x push)\n        (v-z (actor-vel a)) (v-z push)\n        (v-y (actor-vel a)) 11.5\n        (actor-wall-cool a) 0.24\n        (actor-jump-buffer a) 0))','wall'),
s(b('上達できる動きには、制約が要る','Skillful movement needs intentional constraints'),[
b('壁を蹴って高く上がれると、外周壁の上を越える可能性があります。move-bodyは高さにかかわらずx,zを±27.57へ制限し、超えた軸の速度を0へします。壁を無限に高く描くことではなく、遊べる範囲の規則を独立して持っています。これは特殊移動を足すと、元の地図の前提が変わる例です。','Wall kicks can lift an actor above the perimeter wall. move-body clamps x,z to ±27.57 regardless of height and zeroes the blocked axis. Playable bounds are an independent rule rather than infinitely tall visible walls. Adding special movement changes assumptions the original map may have relied on.'),
b('空中でSpaceを押した瞬間はバッファされますが、押し続けるだけで空中の壁キックを無制限に要求するわけではありません。地上の保持ジャンプは別に扱います。操作の改造では、押下、保持、離した時の違いを仕様として書き、指の感触と発動回数の両方で検証します。','A Space press is buffered, but holding Space does not endlessly request airborne kicks. Grounded hold-to-hop is handled separately. When changing controls, specify press, hold, and release behavior, then verify both the feel and the number of activations.')])],
sources:[source('arena.lisp','wall-normal','jump-body'),source('main.lisp','player-input')],
exercise:ex(b('壁キックの反発を20へ強める案を、まず独立した計算で試してください。壁へ向かうwish=(-1,0,0)なら水平速度は？','Test a push strength of 20 in an isolated calculation first. What horizontal velocity results for wish = (-1,0,0) toward the wall?'),b('normal=(1,0,0)、wishの係数は4のままです。','Use normal = (1,0,0) and keep the wish coefficient at 4.'),'(let ((push (v+ (v* (v 1 0 0) 20)\n                 (v* (v -1 0 0) 4))))\n  (assert (= (v-x push) 16)))',b('20−4=16です。実ゲームへ反映する時は跳躍高さ、外周、再発動防止、カメラの演出も確認します。','20−4 = 16. Before applying the change, also check jump height, perimeter behavior, retrigger prevention, and camera feedback.')),
quiz:q(b('この実装の壁キックの水平速度は旧速度へ加算される？','Does this implementation add its horizontal wall-kick push to old velocity?'),[b('はい、毎回加算する','Yes, it always adds it'),b('いいえ、pushで置き換える','No, it replaces the components with push'),b('水平速度は変えない','It leaves horizontal velocity unchanged')],1,b('jump-bodyのsetfを読むと置換だと分かります。式の見た目だけで「ブーストだから加算」と推測しないでください。','The setf in jump-body shows replacement. Do not infer addition merely because the action is called a boost.')),
test:'(make-arena)\n(let ((a (make-actor :pos (v -27.5 2 15) :vel (v -5 -2 0)))) (jump-body a (v 0 0 -1)) (assert (> (v-x (actor-vel a)) 10)) (assert (> (v-y (actor-vel a)) 10)) (let ((n (actor-wall-kicks a))) (jump-body a (v 0 0 -1)) (assert (= n (actor-wall-kicks a)))))',model:true
},
{
id:'hitscan',part:3,minutes:85,title:b('射線に、命中という意味を与える','Give a ray the meaning of a hit'),
subtitle:b('最も近い交差を選ぶだけで、壁越しの命中を防げる。','Selecting the nearest intersection keeps a hit from passing through a wall.'),
goals:[b('ray-boxの区間判定を理解する','Understand ray-box slab intervals'),b('壁とactorの距離を比較する','Compare wall and actor distances'),b('武器の発射条件を一箇所へまとめる','Keep firing eligibility in one place')],
sections:[
s(b('光線と箱が出会う時刻','When a ray meets a box'),[
b('光線はorigin＋direction×tで表します。directionが単位ベクトルならtは距離です。箱の各軸にはlowとhighがあり、dが0でなければt1=(low−origin)/d、t2=(high−origin)/dを計算します。各軸の区間の共通部分が残れば命中です。nearは最大の入口、farは最小の出口になり、near>farなら共通部分はありません。','A ray is origin + direction×t. With a unit direction, t represents distance. Each box axis has low and high bounds. When d is nonzero, compute t1 = (low−origin)/d and t2 = (high−origin)/d. A hit exists if the intervals for all axes overlap. near is the largest entry and far the smallest exit; near > far means no overlap.'),
b('dがほぼ0の軸は割り算しません。その軸でoriginが箱の外なら命中しないし、内なら他軸の判定へ進みます。箱の内部から撃った場合、nearは0を返せます。NILは「命中なし」であり、距離0とは違います。負の方向のt1,t2の順序はminとmaxで入れ替えます。','Do not divide on an axis whose d is nearly 0. If origin lies outside that slab, there is no hit; if inside, continue with the other axes. A ray starting inside a box can return near = 0. NIL means no hit and is different from distance 0. min and max handle reversed entry/exit values for negative directions.')],
'(setf near (max near (min t1 t2))\n      far  (min far  (max t1 t2)))\n(when (> near far)\n  (return-from ray-box nil))','ray'),
s(b('一番手前の対象だけを選ぶ','Choose only the frontmost target'),[
b('hitscanは最初に壁までの距離をnearestへ入れます。各actorのray-actor距離がnearestより短い場合だけ、nearestとvictimを更新します。これで壁の向こうのactorは選ばれません。actorは当たり判定用の箱へ近似されます。描画モデルの輪郭そのものと完全一致する精密な命中判定ではありません。','hitscan initializes nearest with the wall distance. It replaces nearest and victim only when an actor’s ray-actor distance is shorter. An actor behind a wall therefore cannot be selected. Actors use approximate hit boxes, not an exact intersection with the visible character model.'),
b('命中時にhurtを呼び、射線エフェクトを追加します。muzzleは見た目の銃口、判定のoriginは目の位置です。この区別は狙いの分かりやすさを優先しています。銃口そのものから撃つ設計へ変える場合、至近距離の壁やカメラとのずれを検証する必要があります。','A hit calls hurt and adds a beam effect. The visual muzzle and the collision origin are different: collision starts at eye position to keep aiming understandable. Switching to a true muzzle-origin design requires checking nearby walls and parallax relative to the camera.')]),
s(b('武器をルールの表として読む','Read weapons as a set of rules'),[
b('shootはcool<=0、生存中、弾数>0を確かめてから消費し、発射処理へ進みます。イオンはダメージ10・間隔0.105、散弾は11発×9・間隔0.78、ロケットは間隔0.7、レールは90・間隔1.15です。単発ダメージだけで強さは決まりません。命中率、射程感、反動、弾薬供給、射撃中の露出も合わせて設計します。','shoot checks nonpositive cooldown, a living actor, and positive ammo before consuming ammunition. Ion deals 10 every 0.105 second; scatter fires 11 pellets of 9 every 0.78; rockets use a 0.7 interval; rail deals 90 every 1.15. Single-shot damage is not a weapon’s whole balance: accuracy, range, feedback, ammo supply, and exposure also matter.'),
b('散弾は方向へ小さな乱数ベクトルを足し、再びunitで正規化します。これは厳密に一様な円錐分布ではない簡便な散布です。精密な分布が必要なら接線空間で円盤をサンプリングする改造が考えられます。まず現行の性質を数値で確認し、名前だけで理想的な分布だと思わないことです。','Scatter adds a small random vector to direction and normalizes again. This is a simple spread, not a mathematically uniform cone distribution. A more precise design could sample a disk in tangent space. First measure the existing behavior rather than assuming a familiar name guarantees an ideal distribution.')])],
sources:[source('arena.lisp','ray-box','wall-distance','ray-actor','hitscan','shoot')],
exercise:ex(b('原点から+zへ撃ち、z=5に中心、奥行き2の箱へ命中する距離をテストします。横へ外した場合も確認します。','Test a +z ray from the origin toward a box centered at z = 5 with depth 2. Also test a horizontal miss.'),b('箱の手前の面はz=4です。','The front face is at z = 4.'),'(let ((box (make-block :pos (v 0 1 5) :size (v 2 2 2))))\n  (assert (= (ray-box (v 0 1 0) (v 0 0 1) box) 4))\n  (assert (null (ray-box (v 5 1 0) (v 0 0 1) box))))',b('距離と命中なしの両方をテストします。平行軸で割り算しない処理もこの例で通ります。','Test both hit distance and no hit. This example also exercises the branch that avoids division on parallel axes.')),
quiz:q(b('nearestを最初に壁の距離へ設定する理由は？','Why initialize nearest to the wall distance?'),[b('壁の向こうのactorを選ばないため','To reject actors behind the wall'),b('弾数を自動回復するため','To replenish ammo automatically'),b('Lispの括弧を減らすため','To reduce Lisp parentheses')],0,b('actorが壁より近い場合だけ選ばれるので、射線の遮蔽を自然に表せます。','Only actors closer than the wall can become the target, naturally enforcing occlusion.')),
test:'(let ((box (make-block :pos (v 0 1 5) :size (v 2 2 2)))) (assert (= (ray-box (v 0 1 0) (v 0 0 1) box) 4)) (assert (null (ray-box (v 5 1 0) (v 0 0 1) box))))',model:true
},
{
id:'rockets',part:3,minutes:80,title:b('爆発に、時間と反動を与える','Give an explosion time and momentum'),
subtitle:b('ロケットは、飛ぶ物体と範囲内の出来事を組み合わせる。','A rocket combines a moving object with an event affecting its surroundings.'),
goals:[b('弾体を毎刻み更新する','Advance a projectile every step'),b('移動区間の交差を判定する','Test the segment traveled during a step'),b('範囲ダメージとロケットジャンプを作る','Build splash damage and a rocket jump')],
sections:[
s(b('発射の瞬間に完了しない武器','A shot that does not finish immediately'),[
b('hitscanと違い、ロケットはpos、vel、owner、lifeを持ち、*rockets*へ追加されます。初速は方向×34、寿命は4秒です。update-rocketsは古い位置から移動距離travel=dt×速度の長さを求め、その区間で壁またはactorへ当たるかを調べます。最終点だけを判定しないので、その間に薄い壁を飛び越えた命中も捕らえやすくなります。','Unlike hitscan, a rocket stores pos, vel, owner, and life in *rockets*. Initial velocity is direction×34 and lifetime is four seconds. update-rockets computes travel = dt×speed from the old position and checks that segment for wall or actor intersections. Testing the traveled interval rather than only the final point helps catch walls crossed between steps.'),
b('当たった位置の少し手前0.04へ置いてから爆発します。壁の内部に爆発中心を置くと、爆風の遮蔽判定が不自然になるためです。ownerへの直接衝突は飛翔中の判定から外し、爆発の範囲計算では自分も含めます。これにより銃口直後の自己命中を避けながら、足元への射撃をロケットジャンプにできます。','Place the rocket 0.04 units before the intersection before exploding. A blast center inside the wall can distort splash occlusion. Ignore direct flight collision with owner, but include the owner in splash calculations. This avoids an immediate muzzle self-hit while allowing a shot at the feet to become a rocket jump.')]),
s(b('距離によって、効果を弱める','Let distance attenuate the effect'),[
b('半径4.8以内ならscale=1−distance/4.8。通常のダメージはround(115×scale)、自分はround(45×scale)。さらに爆発中心からactor中心までの視線が壁に遮られていないか確認します。単に距離が近いだけで壁の向こうも傷つけると、狭い通路の意味がなくなります。','Within radius 4.8, scale = 1−distance/4.8. Normal damage is round(115×scale); self-damage is round(45×scale). Also test whether a wall blocks the blast center’s line of sight to the actor center. Distance alone would allow splash to damage actors through walls and undermine passage geometry.'),
b('衝撃方向はactor中心−爆心に少し上向き成分を加えてunit化します。自分には26×scale、他者には17×scaleの力を与えます。hpを減らすことと速度を増やすことは別です。保護シールド中の自己ロケットでも反動は残す特例があり、ダメージ処理だけにすべてを押し込んでいません。','For impulse direction, normalize the vector from blast center to actor center with an added upward component. Its magnitude is 26×scale for self and 17×scale for others. Damage and velocity change are separate effects. A special branch preserves self rocket-jump impulse during spawn protection rather than routing every effect through damage eligibility.')],
'(let* ((scale (- 1 (/ distance 4.8)))\n       (damage (round (* 115 scale)))\n       (self-damage (round (* 45 scale))))\n  (list damage self-damage))'),
s(b('短命なオブジェクトの寿命を管理する','Manage a short-lived object’s lifetime'),[
b('delete-ifの判定関数は、爆発した場合または寿命が切れた場合に真を返してロケットを除去します。一つの弾体を二回爆発させないため、移動と除去の責任を同じ更新へ置きます。エフェクトには別のlifeがあり、戦闘の判定が終わったあとも短く見えるようにします。','The predicate passed to delete-if returns true when a rocket explodes or expires, removing it. Put movement and removal in the same update to avoid exploding one projectile twice. Effects have separate lifetimes so visible feedback can remain briefly after combat resolution has finished.'),
b('ロケット速度を大きく変えるなら、長い一区間の判定、爆発の位置、エフェクトの長さを検証します。重力付きグレネードを作る場合は単に武器名を変えるだけでは足りません。弾体のvy更新、床での跳ね返り、時限爆発、botの照準を新たな仕様として組み立てます。','If you greatly change rocket speed, verify segment collision, blast placement, and visible trails. A gravity-driven grenade requires more than renaming a weapon: specify vertical acceleration, floor bounces, timed detonation, and bot aiming as new behavior.')])],
sources:[source('arena.lisp','update-rockets','explode','hurt')],
exercise:ex(b('距離2.4、半径4.8での通常ダメージと自傷ダメージを計算します。距離が半径以上なら0へ制限してください。','Compute normal and self damage at distance 2.4 with radius 4.8. Clamp the effect to 0 when distance reaches or exceeds the radius.'),b('scaleへmax 0を付けます。','Apply max 0 to scale.'),'(defun splash-scale (distance radius)\n  (max 0 (- 1 (/ distance radius))))\n(let ((scale (splash-scale 2.4 4.8)))\n  (list (round (* 115 scale))\n        (round (* 45 scale)))) ; => (58 22)',b('Common Lispのroundはちょうど中間なら偶数側へ丸めます。57.5は58、22.5は22です。別言語へ移植する時に結果が変わりやすい箇所です。','Common Lisp round chooses the even integer at an exact midpoint. 57.5 becomes 58 and 22.5 becomes 22—a detail that can change when porting to another language.')),
quiz:q(b('ロケットの最終位置だけを衝突判定すると起きやすい問題は？','What problem can occur when collision checks only a rocket’s final position?'),[b('薄い壁を飛び越える','Tunneling through thin walls'),b('常に0 FPSになる','Always reaching 0 FPS'),b('弾薬が文字列になる','Ammo turning into a string')],0,b('移動区間内に壁があっても、最終点が外なら見逃します。','A wall crossed during travel can be missed if the final point lies outside it.')),
test:'(assert (= (round 57.5) 58))\n(assert (= (round 22.5) 22))\n(start-match)\n(setf (actor-pos *player*) (v -18 0 -24) (actor-vel *player*) (v 0 0 0) (actor-invuln *player*) 0)\n(explode (make-rocket :pos (v -18 0.1 -24) :vel (v 0 -34 0) :owner *player*))\n(assert (> (v-y (actor-vel *player*)) 10))',model:true
},
{
id:'match',part:3,minutes:80,title:b('戦闘を、一試合へまとめる','Turn combat into a match'),
subtitle:b('HP、装甲、アイテム、復活、勝敗を同じ規則でつなぐ。','Connect health, armor, pickups, respawning, and victory through consistent rules.'),
goals:[b('装甲とHPの消費順を理解する','Understand armor absorption before HP damage'),b('アイテムの回収と再出現を作る','Build pickup collection and respawn timers'),b('試合状態の遷移を設計する','Design match-state transitions')],
sections:[
s(b('ダメージは、一つの入口へ集める','Give damage one entry point'),[
b('hurtは死亡中または保護中なら何もしません。装甲はmin(現在装甲, round(ダメージ×0.6))を吸収し、残りがHPを減らします。ダメージ100、装甲25なら装甲は25だけ吸収し、HPは75減ります。装甲を先に0へした後で吸収量を計算すると、使うべき旧値を失います。','hurt does nothing while the victim is dead or protected. Armor absorbs min(current armor, round(damage×0.6)); the remainder reduces HP. For damage 100 and armor 25, armor absorbs 25 and HP loses 75. Zeroing armor before computing absorption would lose the old value needed by the rule.'),
b('HPが0以下になると、死亡数、復活タイマー、得点、キルフィードを更新します。他者を倒した場合はattackerに+1、自爆ならvictimに-1です。判定の入口が一つなので、レールと散弾と爆風で得点の条件が別々に壊れることを減らせます。衝撃も受け取れますが、保護中の自己反動の特例はexplode側です。','When HP reaches 0 or below, update deaths, respawn timer, score, and kill feed. A kill awards +1 to attacker; suicide subtracts 1 from victim. A shared entry point reduces inconsistent scoring across rail, scatter, and splash. hurt can receive impulse, but the protected self-impulse exception lives in explode.')],
'(let* ((damage 100) (armor 25)\n       (absorb (min armor (round (* damage 0.6))))\n       (hp-loss (- damage absorb)))\n  (list absorb hp-loss)) ; => (25 75)','damage'),
s(b('回収できた時だけ、時計を動かす','Start a pickup timer only when collection succeeds'),[
b('healthは100未満のHPを35回復、megaは175まで75回復、armorは150まで60追加します。既に上限ならtakenをNILにし、タイマーを開始しません。弾薬は武器別のarefへ追加します。回収したmegaは30秒、その他は18秒で再出現します。アイテムの見た目の浮遊は判定位置そのものではありません。','Health restores 35 up to 100, mega restores 75 up to 175, and armor adds 60 up to 150. If already at the limit, taken becomes NIL and no timer starts. Ammo writes to the corresponding weapon index. Mega respawns after 30 seconds, other pickups after 18. The visual bobbing is separate from the collision position.'),
b('update-pickupsはtimerを減らし、有効なアイテムに近い生存actorを調べます。複数人が同時に触れていても、最初の回収でtimerが正になるので同じ更新中の二重回収を避けます。actor順が同時回収の優先を決める点は、この逐次更新の設計上の性質です。','update-pickups decreases timers and tests nearby living actors against active items. The first successful collection makes the timer positive, preventing another collection in the same update. Actor order determines priority in a simultaneous case—an explicit property of sequential updates.')]),
s(b('画面ではなく、状態を切り替える','Change state rather than just changing a screen'),[
b('*state*は:menu、:playing、:paused、:resultsです。更新が進むのは:playingだけ。死者は2秒後にspawn-actorで復活し、1.8秒の保護を得ます。射撃はその保護を解除します。start-matchはactor、弾薬、アイテム、得点、時計を作り直します。前試合のロケットが残らないことも初期化の仕事です。','*state* is :menu, :playing, :paused, or :results. Only :playing advances the simulation. Dead actors respawn after two seconds with 1.8 seconds of protection; firing cancels it. start-match reconstructs actors, ammo, pickups, scores, and clock. Removing rockets from the previous match is part of initialization.'),
b('規定得点または5分の時間切れで:resultsへ移ります。現行の順位は得点で安定ソートするので、同点ではactor順が残ります。本格的な引き分けや延長戦を作るなら、勝者の表示だけでなく、終了条件と順位規則を合わせて変更します。','Reaching the frag limit or five-minute timeout moves to :results. Current standings use a stable score sort, so actor order remains for tied scores. A proper draw or overtime rule needs changes to termination and ranking as well as the winner’s text.')])],
sources:[source('arena.lisp','hurt','collect-pickup','update-pickups','spawn-actor','start-match','tick-game')],
exercise:ex(b('HPが100のactorに通常healthを回収させ、アイテムが消えないことをassertします。次にHP40で回収し、75になることを確かめます。','Assert that an actor at HP 100 cannot consume normal health. Then collect it at HP 40 and verify HP 75.'),b('pickup-timerも回収成功の結果として確認します。','Also check pickup-timer as an observable collection result.'),'(let ((a (make-actor :pos (v 0 0 0)))\n      (item (make-pickup :pos (v 0 0 0) :kind :health)))\n  (collect-pickup a item)\n  (assert (= (pickup-timer item) 0))\n  (setf (actor-hp a) 40)\n  (collect-pickup a item)\n  (assert (= (actor-hp a) 75))\n  (assert (> (pickup-timer item) 0)))',b('数値だけでなく、「回収できなかった時はアイテムを消さない」という仕様まで検証します。','This verifies not just the numbers but the rule that an unsuccessful collection leaves the item available.')),
quiz:q(b('ダメージ100、装甲25で失うHPは？','How much HP is lost with damage 100 and armor 25?'),[b('40','40'),b('75','75'),b('100','100')],1,b('60を吸収したくても装甲は25しかありません。残り75がHPへ通ります。','The desired absorption is 60, but only 25 armor exists. The remaining 75 reaches HP.')),
test:'(let ((a (make-actor :pos (v 0 0 0))) (item (make-pickup :pos (v 0 0 0) :kind :health))) (collect-pickup a item) (assert (= (pickup-timer item) 0)) (setf (actor-hp a) 40) (collect-pickup a item) (assert (= (actor-hp a) 75)) (assert (> (pickup-timer item) 0)))',model:true
},
{
id:'navigation',part:3,minutes:95,title:b('botに、道を見つけさせる','Teach a bot to find a path'),
subtitle:b('歩ける場所をグラフにして、A*で目的地へ結ぶ。','Make walkable space into a graph and connect it with A*.'),
goals:[b('地形をノードと辺へ変換する','Convert geometry into nodes and edges'),b('A*のg・h・fを区別する','Distinguish A*’s g, h, and f'),b('経路の復元と到達不能を扱う','Recover a path and handle unreachable goals')],
sections:[
s(b('連続した世界を、点の集合にする','Sample a continuous world into nodes'),[
b('build-navはx,zを1.5間隔でサンプリングし、floor-atで高さを求めます。壁へ近すぎる点や高すぎる点を除外して、*nav*へ位置を入れます。近傍へは8方向に辺を張り、上昇2.0以下、下降5.0以下の範囲へ制限します。斜め移動は隣の直交セルも必要とし、壁の角を横切る近道を減らします。','build-nav samples x,z every 1.5 units and queries heights with floor-at. It excludes points too close to walls or too high, then stores positions in *nav*. Eight-direction edges allow rises up to 2.0 and drops up to 5.0. Diagonal movement also requires adjacent orthogonal cells to reduce corner cutting.'),
b('これは万能のナビメッシュではありません。各x,zで一つの高さを選ぶので、上下に通路が重なる橋や地下道を同時に表せません。空間を大きく改造する時は複数層のノードやメッシュへ変える必要があります。小さなアリーナでは、その制約を理解した簡単なグラフが読みやすい選択です。','This is not a universal navigation mesh. One sampled height per x,z cannot represent overlapping routes such as a bridge above a tunnel. Such a map needs multilayer nodes or a mesh. In this small arena, a simple graph is readable when its limitation is understood.')]),
s(b('A*は、どの候補を次に調べるか','A* decides which candidate to explore next'),[
b('gは出発点から今のノードまでの既知の費用、hは目的地までの推定距離、f=g+hです。routeはopenからfが最小のノードを選び、隣接ノードへ進む費用を更新します。既に調べたclosedは再処理しません。辺の費用もhも三次元の距離なので、このグラフでは直線距離が過大な見積もりになりません。','g is known cost from start to a node, h is estimated distance to the goal, and f = g+h. route selects the smallest-f node from open and improves neighbor costs. closed prevents reprocessing visited nodes. Both edge cost and h use three-dimensional distance, so straight-line h does not overestimate costs in this graph.'),
b('費用が改善したときparent[next]=currentを保存します。ゴールへ到達したらparentを逆にたどり、nreverseで進む順へ戻します。start自身は経路に含めません。startとendが同じノードならNILという空の経路になり、到達不能のNILと区別できません。この戻り値設計を改善するなら、第二値で状態を返す方法があります。','When a cost improves, store parent[next] = current. At the goal, follow parents backward and nreverse the result into movement order. The start node is omitted. If start and end are the same, the empty path is NIL, indistinguishable from unreachable NIL. A second return value could improve that contract.')],
'; A* priority\n(+ (aref cost node)\n   (distance3 (aref *nav* node) (aref *nav* end)))\n\n; When a better route reaches next:\n(setf (aref cost next) new-cost\n      (aref parent next) current)','nav'),
s(b('小さな探索を、観察してから速くする','Observe a small search before optimizing it'),[
b('openはリストで、reduceによる最小候補選択は候補数に比例します。巨大な世界には優先度キューが向きますが、この数百点のアリーナでは実装を理解する方が重要です。経路を毎更新求めず、botのthinkタイマーで間隔を空けることも性能の一部です。','open is a list; selecting its minimum with reduce costs time proportional to the candidate count. Large worlds may need a priority queue, but understanding the small implementation matters here. Performance also depends on using the bot’s think timer rather than recomputing a route every update.'),
b('図の実験室は平面のA*です。セルをクリックまたは選択欄で障害物を変え、一手ずつopenからclosedへ移す様子を見ます。実ゲームの高さ制限はこの図には含みません。実マップではrouteの有無に加え、botがその経路を身体で通れることまで確認してください。','The lab shows planar A*. Toggle obstacles with pointer input or keyboard controls, then step candidates from open to closed. It does not model the real map’s height limits. In the actual arena, verify not only that route returns a path but that the bot’s body can follow it.')])],
sources:[source('arena.lisp','build-nav','nearest-node','route')],
exercise:ex(b('外周の低い出発点から、東の上段の武器位置まで経路を求め、最後のノードが目的地の近くにあることを確認します。','Find a route from a low perimeter spawn to the weapon on the east terrace, and verify that its last node is near the destination.'),b('目的地そのものではなく、nearest-nodeへ終わる点に注意します。','The route ends at nearest-node, not necessarily at the exact requested point.'),'(make-arena)\n(let* ((goal (v 22 3.2 7))\n       (path (route (v -20 0 -24) goal)))\n  (assert path)\n  (assert (< (distance3 (car (last path)) goal) 2.0)))',b('探索のゴールと実際のアイテム位置の差を許容しています。取得範囲との関係もbot実行で確認します。','The assertion allows for the gap between the sampled goal and actual pickup position. Bot execution must also check that pickup reach covers that gap.')),
quiz:q(b('A*のfは何を表す？','What is f in A*?'),[b('g+h','g+h'),b('FPS','FPS'),b('HP×装甲','HP×armor')],0,b('既知の費用と残りの推定費用を足して、候補を比較します。','It combines the known cost with estimated remaining cost to compare candidates.')),
test:'(make-arena)\n(let* ((goal (v 22 3.2 7)) (path (route (v -20 0 -24) goal))) (assert path) (assert (< (distance3 (car (last path)) goal) 2.0)))',model:true
},
{
id:'bots',part:3,minutes:90,title:b('敵に、判断と迷いを与える','Give an opponent decisions and uncertainty'),
subtitle:b('見える、狙う、移動する。独立した判断を同じ身体へ渡す。','Seeing, aiming, and moving are separate decisions sharing one physical body.'),
goals:[b('可視判定と目標選択をつなぐ','Connect visibility and target selection'),b('経路追従と戦闘移動を分ける','Separate path following from combat movement'),b('難易度を観察できる値で調整する','Tune difficulty through observable parameters')],
sections:[
s(b('botは、特別な物理を持たない','A bot does not get special physics'),[
b('botもactorであり、accelerate、jump-body、move-body、shootを共有します。判断だけがupdate-botです。choose-targetは生存中の相手を距離50以内から選び、visibleで壁に遮られていないことを調べます。敵の位置を知っていても、その方向へ壁越しに撃つのを防ぐために知識と視認を分けています。','A bot is an actor sharing accelerate, jump-body, move-body, and shoot with the player. update-bot supplies decisions. choose-target looks for living opponents within 50 units and visible checks occlusion. Knowing an opponent’s position and being able to see it are separate questions, preventing wall-blind shooting.'),
b('thinkは0.3〜0.65秒ごとに目標と経路を更新します。敵が見えれば敵へ、そうでなければ不足しているHPや装甲、弾薬へ向かいます。choose-goalは価値−距離コストで候補を採点します。これは学習AIではなく、明示的に書いた行動規則です。どの値が選択を変えるか追跡できます。','think refreshes target and route every 0.3–0.65 second. A visible opponent becomes a combat goal; otherwise pickups address missing health, armor, or ammo. choose-goal scores value minus distance cost. This is hand-written decision logic, not a learned AI, so you can trace which values change a decision.')]),
s(b('経路と、戦闘の足取り','Following a route and moving in combat'),[
b('通常は経路の最初の点へwishを作り、十分近くなったらpopします。上の点を目指すときや停滞時にはジャンプを要求します。近い敵との戦闘では前進・後退と横移動を混ぜます。距離7未満では少し退き、左右の横移動は時刻に沿って切り替えます。移動に変化があっても、最終的には同じwishで加速します。','Normally the bot creates wish toward the first path point and pops it when close enough. It requests jumps for higher points or when stuck. Nearby combat combines approach, retreat, and strafing. Within 7 units it retreats slightly; time-varying strafe direction changes its lateral motion. All of these still produce the same wish input to acceleration.'),
b('stuckは前更新とほとんど位置が変わらない時間を積み上げます。長く詰まれば経路を再考します。これは複雑な局所回避の代わりの簡単な復旧です。bot同士の身体衝突は実装していないため、重なり得ます。将来追加するなら、回避とターゲット方向が同じ位置になる場合の処理も必要です。','stuck accumulates time with almost no movement. Persistent blockage triggers replanning. It is a simple recovery mechanism rather than sophisticated local avoidance. Bot bodies do not currently collide with one another and can overlap. Adding that feature also requires avoiding and aiming safely when positions coincide.')]),
s(b('難しさを、当てやすさだけにしない','Difficulty can be more than aim accuracy'),[
b('現行の3難易度は主に照準誤差0.10、0.047、0.016で差を作ります。距離が長いほど小さな角度誤差が大きな外れになります。武器は遠くでレール、中距離でロケット、近くで散弾を選びます。ロケットだけは距離/34秒ぶんの相手速度を足して先読みします。','The three current difficulty levels differ mainly through aim errors 0.10, 0.047, and 0.016. A small angular error becomes a larger miss at distance. Bots prefer rail at long range, rockets at medium range, and scatter nearby. Rockets alone lead the target by approximately distance/34 seconds of its velocity.'),
b('発射の確率判定は毎更新繰り返されるので、0.65へ下げても長い反応遅延を意味しません。独立したreactionタイマーを追加すれば、初心者向けの難易度をより説明しやすくできます。検証は「botが動く」だけで終わらず、移動距離、拾った物、命中、撃破、詰まりの回数で行います。','A firing probability is retried each update, so 0.65 is not the same as a long reaction delay. An explicit reaction timer would make beginner difficulty easier to explain and tune. Verify more than “the bot moves”: inspect distance traveled, pickups, hits, kills, and stuck recoveries.')])],
sources:[source('arena.lisp','visible','choose-target','choose-goal','update-bot')],
exercise:ex(b('距離20、ロケット速度34、敵速度(6,0,0)なら先読み位置の追加分を求めます。','Compute lead displacement at distance 20, rocket speed 34, and target velocity (6,0,0).'),b('飛翔時間は20/34秒です。','Flight time is 20/34 seconds.'),'(let ((lead (v* (v 6 0 0) (/ 20 34))))\n  (assert (= (v-x lead) 60/17)))',b('これは一定速度の近似です。敵の加速や障害物を予測する解ではありませんが、先読みの出発点になります。','This is a constant-velocity approximation, not a prediction of acceleration or obstacles. It is a useful first step in leading a target.')),
quiz:q(b('botの経路を毎120 Hz更新で作り直すことの問題は？','What is a cost of rebuilding every bot route at 120 Hz?'),[b('不要な探索費用が増える','It adds unnecessary search work'),b('必ず精度がゼロになる','It always reduces accuracy to zero'),b('Common Lispが使えなくなる','It makes Common Lisp unusable')],0,b('判断周期と身体更新周期は別でよいので、必要な時だけ再探索します。','Decision and physics rates can differ; replan when needed.')),
test:'(make-arena)\n(let ((lead (v* (v 6 0 0) (/ 20 34)))) (assert (= (v-x lead) 60/17)))\n(let ((*bot-count* 2) (*frag-limit* 10000) (*random-state* (sb-ext:seed-random-state 42))) (start-match) (setf (actor-bot *player*) t) (dotimes (i 3600) (tick-game +tick+ (v 0 0 0) nil nil)) (assert (> (reduce #\'+ *actors* :key #\'actor-shots) 10)))',model:true
},
{
id:'presentation',part:3,minutes:75,title:b('手応えを、画面と音へ翻訳する','Translate an action into visual and audio feedback'),
subtitle:b('数値として正しいゲームを、読めるゲームにする。','Make a numerically correct game legible to its player.'),
goals:[b('描画と状態の変更を分離する','Keep drawing separate from state mutation'),b('解像度に依存しないHUDを作る','Build a resolution-independent HUD'),b('短いエフェクトと距離減衰を理解する','Understand transient effects and audio attenuation')],
sections:[
s(b('描くのは、今の世界','Draw the world that already exists'),[
b('render-frameは3Dを描いてから2DのHUDを重ねます。menuではカメラをゆっくり回し、playingではeyeからyaw,pitch方向を見ます。recoilは発射時に1へ上げ、タイマーで減らし、銃の位置と銃口の発光に使います。命中表示はhit-flash、被弾はdamage-flashです。表示のためにダメージを二度適用しないことが重要です。','render-frame draws 3D, then overlays the 2D HUD. Menu uses an orbiting camera; playing looks from eye along yaw and pitch. Shooting sets recoil to 1, timers decay it, and drawing uses it for weapon motion and muzzle flash. hit-flash and damage-flash indicate hits and damage. Feedback must not apply the damage again.'),
b('カメラの揺れや画角の速度変化は操作感を強めますが、強すぎると狙いにくくなります。現行の速度画角は水平速度12を超えた分へ0.35を掛けて足します。raylibのcam.fovyは垂直画角です。一般的なFPSの水平FOV数値と同じ意味だと決めつけないでください。','Camera motion and speed-dependent FOV can strengthen feedback, but excessive effects make aiming harder. The current FOV adds 0.35 times horizontal speed above 12. raylib cam.fovy is a vertical field of view. Do not assume its number means the same thing as a horizontal-FOV setting in another FPS.')]),
s(b('HUDを、仮想的な紙へ描く','Draw the HUD on a virtual sheet'),[
b('HUDの設計座標は1280×720です。ui-scale=min(width/1280,height/720)で縮尺を求め、余りを左右・上下の余白にします。ux,uyは設計座標を実画面へ変換します。ボタンの当たり判定では逆にマウス座標を設計座標へ戻します。描画と入力で片方だけ縮尺を使うと、クリック位置がずれます。','The HUD uses a virtual 1280×720 coordinate space. ui-scale = min(width/1280,height/720) supplies scale, with remaining space centered as margins. ux and uy transform design positions to screen positions; button hit-testing transforms the mouse back. Scaling drawing but not input produces misaligned clicks.'),
b('色と数値だけで情報を伝えず、HEALTH、ARMOR、武器名のラベルを残します。minimapは形を縮小し、近くの敵だけを表示します。TABの順位はcopy-listで本体のactor順を変更せず並べ替えます。HUDの変更でもゲームモデルへ副作用が入らないかを考えます。','Keep HEALTH, ARMOR, and weapon labels instead of relying only on color and numbers. The minimap scales geometry and shows nearby enemies. TAB standings sort a copy of actors without reordering the simulation. Even presentation changes should be checked for accidental model mutation.')],
'(setf *ui-scale*\n      (min (/ (ss-width) 1280.0)\n           (/ (ss-height) 720.0)))\n(defun ux (x) (+ *ui-left* (* x *ui-scale*)))'),
s(b('音に距離を持たせる','Give a sound a distance'),[
b('sound-atはgain/(1+0.07×distance)で音量を弱めます。分母の1が重要です。単に0.07×distanceで割ると、自分の位置で鳴る音は距離0となってゼロ除算します。パンは視線の右方向と音源方向の内積から求め、0.05〜0.95に制限します。正しい数値でも、左右の聞こえ方は実機で確かめます。','sound-at attenuates volume with gain/(1+0.07×distance). The 1 matters: dividing only by 0.07×distance causes division by zero for a sound at the listener. Panning uses the dot product of the listener’s right direction and the source direction, clamped to 0.05–0.95. Numerical correctness still needs an actual listening check.'),
b('bridge.cの音はPCM波形を生成してraylibへ読み込ませます。外部の効果音素材に依存しません。衝突テストが通ることは音が聞こえる証明ではありません。同じようにコンパイル成功はHUDの読める配置の証明でもありません。UI・音・性能の変更には、実際に表示する、聞く、測るという検証を追加します。','bridge.c generates PCM waveforms and loads them into raylib without external sound assets. A passing collision test does not prove that sound is audible; a successful compile does not prove that HUD layout is legible. Presentation, audio, and performance changes need display inspection, listening, or measurement respectively.')],
'(/ 1 (+ 1 (* 0.07 0)))  ; => 1, safe at the listener\n(/ 1 (+ 1 (* 0.07 20))) ; approximately 0.417','sound')],
sources:[source('view.lisp','render-frame','render-hud','button'),source('arena.lisp','sound-at')],
exercise:ex(b('sound-atの減衰式を独立した関数へ書き、距離0と20で有限の非負値が返ることを確認します。','Write the attenuation formula as an isolated function, then verify finite nonnegative values at distances 0 and 20.'),b('分母が常に1以上ならゼロ除算を防げます。','A denominator of at least 1 prevents division by zero.'),'(defun attenuation (distance)\n  (/ 1 (+ 1 (* 0.07 (max 0 distance)))))\n(assert (= (attenuation 0) 1))\n(assert (< 0 (attenuation 20) 1))',b('実ゲームの不具合を再現できる最小計算で、修正の意味を確かめています。','This verifies a real fix through the smallest calculation that can reproduce the bug.')),
quiz:q(b('HUDを拡大したとき、マウス判定にも必要なものは？','What else must be transformed when the HUD is scaled?'),[b('クリック座標の逆変換','The inverse transform for click coordinates'),b('弾薬を二倍にする','Doubling ammo'),b('重力の削除','Removing gravity')],0,b('描画と入力が同じ設計座標を使う必要があります。','Drawing and input must agree on the same design coordinate space.')),
test:'(assert (= (/ 1 (+ 1 (* 0.07 0))) 1))\n(assert (< 0 (/ 1 (+ 1 (* 0.07 20))) 1))'
}
];
